var CRYSTALS = [
    {
        code: 'DLR_AMR',    name: "Dark Lord's Armor",
        type: ARMOR,        material: CRYS,
        score: 2308,        slots: 'GOO_4-HEA_5-REC-TRI-KIT|CIR',
        cost: 38,
    },
    {
        code: 'DLR_HLM',    name: "Dark Lord's Helm",
        type: HEAD,         material: CRYS,
        score: 4093,        slots: 'GOO_4-DRKD_5-CIR-DAI-REC|TRI',
        cost: 38,
    },
    {
        code: 'FAR_BUR',    name: "Farburfall",
        type: HEAD,         material: CRYS,
        score: 3953,        slots: 'SWA_4-SKL_5-HP_5-DAI-CIR|DAI',
        cost: 35,
    },
    {
        code: 'FLU_SUI',    name: "One Winged Suit Flugel",
        type: ARMOR,        material: CRYS,
        score: 2283,        slots: 'SWA_4-FIRD_5-CMB_5-CIR-KIT|CIR',
        cost: 35,
    },
    {
        code: 'GAI_AMR',    name: "Gaia Armor",
        type: ARMOR,        material: CRYS,
        score: 2305,        slots: 'DOA_4-SKG_5-HAS_5-SKL_5-CIR|CIR',
        cost: 34,
    },
    {
        code: 'GAI_HLM',    name: "Gaia Helm",
        type: HEAD,         material: CRYS,
        score: 3883,        slots: 'DOA_4-HEA_5-SKA_4-CIR-KIT|TRI',
        cost: 34,
    },
    {
        code: 'ISR_GAR',    name: "Holy Garment of Israfil",
        type: ARMOR,        material: CRYS,
        score: 2265,        slots: 'MCR_4-HEA_5-CIR-CIR-REC|CIR',
        cost: 34,
    },
    {
        code: 'ISR_MTR',    name: "Israfil Mitra",
        type: HEAD,         material: CRYS,
        score: 3815,        slots: 'MCR_4-SKL_5-SKG_3-TRI-TRI|TRI',
        cost: 34,
    },
    {
        code: 'QUA_HAT',    name: "Quasar Tiara",
        type: HEAD,         material: CRYS,
        score: 4564,        slots: 'DOA_5-ATK_10-HP_9-TRI-TRI|TRI',
        limited: true,      cost: 40,
        name2: "Quasar Hat",
    },
    {
        code: 'QUA_SUI',    name: "Quasar Suit",
        type: ARMOR,        material: CRYS,
        score: 2553,        slots: 'DOA_5-SKL_9-REC-CIR-KIT|CIR',
        limited: true,      cost: 40,
    },
    {
        code: 'HLM_DET',    name: "Helm of the Darkeater",
        type: HEAD,         material: CRYS,
        score: 4254,        slots: 'GOO_5-CMB_10-SKG_8-TRI-CIR|KIT',
        cost: 37,
    },
    {
        code: 'MAI_DET',    name: "Mail of the Darkeater",
        type: ARMOR,        material: CRYS,
        score: 2385,        slots: 'GOO_5-HAS_10-HEA_8-REC-TRI|CIR',
        cost: 37,
    },
    {
        code: 'HLY_CXM',    name: "Holy Cruxta Mail",
        type: ARMOR,        material: CRYS,
        score: 2370,        slots: 'DOA_5-KOH_5-ADH_4-REC-TRI|KIT',
        cost: 37,
    },
    {
        code: 'TRR_CXM',    name: "Terra Cruxta Helmet",
        type: HEAD,         material: CRYS,
        score: 4299,        slots: 'DOA_5-SKR_5-HEA_9-CIR-TRI|TRI',
        cost: 37,
    },
    {
        code: 'NYD_HAT',    name: "New Year Delivery Hat",
        type: HEAD,         material: CRYS,
        score: 3388,        slots: 'KTS_4-SPS_5-SKL_8-CIR-KIT|CIR',
        evt: true,          cost: 30,
        brave_rate: 2,
    },
    {
        code: 'NYD_COA',    name: "New Year Delivery Coat",
        type: ARMOR,        material: CRYS,
        score: 2088,        slots: 'KTS_4-HEA_5-HAS_8-CIR-CIR',
        evt: true,          cost: 30,
        brave_rate: 2,
    },
    {
        code: 'RAL_HLM',    name: "Brilliant Alexander's Helm",
        type: HEAD,         material: CRYS,
        score: 4356,        slots: 'GOO_5-CMB_9-KOH_5-TRI-KIT|CIR-REC',
        cost: 37,
    },
    {
        code: 'BAL_COA',    name: "Brilliant Alaxandria Coat",
        type: ARMOR,        material: CRYS,
        score: 2493,        slots: 'GOO_5-QUI_4-HEA_10-CIR-TRI|TRI',
        cost: 37,
    },
    {
        code: 'VSG_NVL',    name: "Visage of Noble Valor",
        type: HEAD,         material: CRYS,
        score: 4777,        slots: 'TOP_5-HEA_10-SRS_5-TRI-REC|DAI-CIR',
        limited: true,        cost: 50,
    },
    {
        code: 'GCK_NVL',    name: "Greatclock of Noble Valor",
        type: ARMOR,        material: CRYS,
        score: 2777,        slots: 'TOP_5-SUR_5-SPB_4-CIR-TRI|KIT-TRI',
        limited: true,      cost: 50,
    },
    {
        rcode: 9017,        name: "High Sheriff Hat",
        type: HEAD,         material: CRYS,
        score: 3400,        slots: 'MCR_4-HEA_5-DEF_9-TRI-REC',
        evt: true,          cost: 0,
        brave_rate: 2,
    },
    {
        rcode: 9017,        name: "High Sheriff Jacket",
        type: ARMOR,        material: CRYS,
        score: 2130,        slots: 'MCR_4-DMH_5-SKL_9-CIR-DAI',
        evt: true,          cost: 0,
        brave_rate: 2,
    },
    {
        rcode: 3023,        name: "Bounty Hunter Hat",
        type: HEAD,         material: CRYS,
        score: 3927,        slots: 'SWA_4-HAS_5-ATK_8-TRI-CIR',
        evt: true,          cost: 34,
    },
    {
        rcode: 3023,        name: "Bounty Hunter Jacket",
        type: ARMOR,        material: CRYS,
        score: 2207,        slots: 'SWA_4-HVH_5-CMB_8-CIR-DAI',
        evt: true,          cost: 34,
    },
    {
        rcode: 3037,        name: "Helm of Holy Light+",
        type: HEAD,         material: CRYS,
        score: 4009,        slots: 'SBI_4-DRKD_5-CMB_10-CIR-CIR',
        evt: true,          cost: 37,
    },
    {
        rcode: 3037,        name: "Harness of Holy Light+",
        type: ARMOR,        material: CRYS,
        score: 2347,        slots: 'SBI_4-DRKD_5-HP_10-TRI-TRI',
        evt: true,          cost: 37,
    },
    {
        rcode: 3037,        name: "Helm of Holy Light",
        type: HEAD,         material: CRYS,
        score: 3061,        slots: 'SBI_2-DRKD_4-CMB_5-CIR-CIR',
        evt: true,          cost: 31,
    },
    {
        rcode: 3037,        name: "Harness of Holy Light",
        type: ARMOR,        material: CRYS,
        score: 1505,        slots: 'SBI_2-DRKD_4-HP_5-TRI-TRI',
        evt: true,          cost: 31,
    },
    {
        rcode: 3056,        name: "Helmet of Cavaliere+",
        type: HEAD,         material: CRYS,
        score: 4043,        slots: 'MCR_4-ELED_5-CMB_10-CIR-CIR',
        evt: true,          cost: 37,
    },
    {
        rcode: 3056,        name: "Armor of Equitatus+",
        type: ARMOR,        material: CRYS,
        score: 2365,        slots: 'MCR_4-ELED_5-ATK_10-TRI-REC',
        evt: true,          cost: 37,
    },
    {
        rcode: 3056,        name: "Helmet of Cavaliere",
        type: HEAD,         material: CRYS,
        score: 3926,        slots: 'MCR_4-ELED_5-CMB_8-CIR-CIR',
        evt: true,          cost: 34,
    },
    {
        rcode: 3056,        name: "Armor of Equitatus",
        type: ARMOR,        material: CRYS,
        score: 2131,        slots: 'MCR_4-ELED_5-ATK_8-TRI-REC',
        evt: true,          cost: 34,
    },
    {
        rcode: 3081,        name: "Cobalt Moon Halcyon",
        type: HEAD,         material: CRYS,
        score: 4500,        slots: 'WSM_5-HEA_9-EFR_5-CIR-CIR|TRI',
        cost: 42,
    },
    {
        rcode: 3081,        name: "Cobalt Lumina Halcyon",
        type: ARMOR,        material: CRYS,
        score: 2530,        slots: 'WSM_5-VSP_5-HTF_4-CIR-TRI|CIR',
        cost: 42,
    },
    {
        rcode: 3072,        name: "Adamant Cerulean Helm",
        type: HEAD,         material: CRYS,
        score: 4680,        slots: 'GOO_5-EFR_5-HEA_10-REC-CIR|DAI',
        cost: 42,
    },
    {
        rcode: 3072,        name: "Adamant Cerulean Mail",
        type: ARMOR,        material: CRYS,
        score: 2580,        slots: 'GOO_5-EFR_5-VSP_5-CIR-KIT|TRI',
        cost: 42,
    },
    {
        rcode: 3087,        name: "Evil Knight Facade",
        type: HEAD,         material: CRYS,
        score: 4770,        slots: 'JWF_5-KOH_5-SSL_5-DAI-REC|KIT',
        cost: 42,
    },
    {
        rcode: 3087,        name: "Evil Knight Armor",
        type: ARMOR,        material: CRYS,
        score: 2630,        slots: 'JWF_5-SPB_5-EFR_5-CIR-TRI|CIR-TRI',
        cost: 42,
    },
    {
        rcode: 3079,        name: "Headdress of Pure Grace",
        type: HEAD,         material: CRYS,
        score: 4455,        slots: 'SWA_4-FIRD_5-BBL_5-CIR-CIR',
        cost: 42,           evt: true,
        name2: 'Mask of Honor',
    },
    {
        rcode: 3079,        name: "Blooming Grace",
        type: ARMOR,        material: CRYS,
        score: 2440,        slots: 'SWA_4-DRKD_5-QHT_5-REC-CIR|CIR',
        cost: 42,           evt: true,
        name2: 'Dance Cloak of Valor',
    },
    {
        rcode: 9021,        name: "Blooming Evening Star",
        type: HEAD,         material: CRYS,
        score: 3630,        slots: 'TOP_4-DRKD_5-MGR_4-TRI-CIR|REC',
        cost: 42,           evt: true,
        brave_rate: 2,
    },
    {
        rcode: 9021,        name: "Graceful Evening Star",
        type: ARMOR,        material: CRYS,
        score: 2147,        slots: 'TOP_4-FIRD_5-EFR_4-REC-CIR|DAI',
        cost: 42,           evt: true,
        brave_rate: 2,
    },
    {
        rcode: 3098,        name: "Sapient Penemue Helm",
        type: HEAD,         material: CRYS,
        score: 4972,        slots: 'LSG_6-TMV_6-SOG_5-REC-TRI|DAI-CIR',
        cost: 50,           limited: true,
    },
    {
        rcode: 3098,        name: "Sapient Penemue Mail",
        type: ARMOR,        material: CRYS,
        score: 2908,        slots: 'LSG_6-VSP_6-MGR_5-CIR-REC|TRI-CIR',
        cost: 50,           limited: true,
    },
    {
        rcode: 1020,        name: "Crimson Dragon's Helm",
        type: HEAD,         material: CRYS,
        score: 4870,        slots:  'AVG_5-SOG_6-EFR_5-CIR-KIT|DAI',
        cost: 42,           slots2: 'AVG_5-SOG_6-EFR_5-CIR-TRI|DAI',
    },
    {
        rcode: 1020,        name: "Crimson Dragon's Mail",
        type: ARMOR,        material: CRYS,
        score: 2770,        slots:  'AVG_5-SOG_6-HWL_5-CIR-KIT|REC',
        cost: 42,           slots2: 'AVG_5-SOG_6-HWL_5-CIR-TRI|REC',
    },
    {
        rcode: 9026,        name: "Sand Gold Helm",
        type: HEAD,         material: CRYS,
        score: 4620,        slots: 'GOO_5-DRKD_5-SSL_4-TRI-CIR|TRI',
        cost: 42,           evt: true,
    },
    {
        rcode: 9026,        name: "Sand Gold Armor",
        type: ARMOR,        material: CRYS,
        score: 2650,        slots: 'GOO_5-FIRD_5-TMV_4-CIR-REC|KIT',
        cost: 42,           skill: 'ICE_BST_1',
        evt: true,
    },
    {
        rcode: 3104,        name: "Crimson Siege Helm",
        type: HEAD,         material: CRYS,
        score: 5025,        slots: 'SMR_6-WLW_6-TMV_5-TRI-TRI|CIR-KIT',
        cost: 45,           limited: true,
    },
    {
        rcode: 3104,        name: "Crimson Siege Mail",
        type: ARMOR,        material: CRYS,
        score: 3000,        slots: 'SMR_6-SCT_5-MGR_6-TRI-DAI|KIT-CIR',
        cost: 45,           skill: 'BLZ_OBT_3',
        limited: true,
    },
    {
        rcode: 3102,        name: "Siren's Shining Headpiece",
        type: HEAD,         material: CRYS,
        score: 4530,        slots: 'WSM_4-MSM_5-KOH_4-REC-CIR|CIR',
        cost: 45,           evt: true,
    },
    {
        rcode: 3102,        name: "Siren's Shining Tallith",
        type: ARMOR,        material: CRYS,
        score: 2630,        slots: 'WSM_4-HRF_4-ELF_5-CIR-REC|CIR-TRI',
        cost: 45,           skill: 'WND_SHF_3',
        evt: true,
    },
    {
        rcode: 3114,        name: "Yue Shen Helm",
        type: HEAD,         material: CRYS,
        score: 5040,        slots: 'WRC_5-HWL_6-HWL_5-CIR-KIT|TRI-DAI',
        cost: 45,
    },
    {
        rcode: 3114,        name: "Yue Shen Mail",
        type: ARMOR,        material: CRYS,
        score: 3000,        slots: 'WRC_5-SPB_6-SPB_5-CIR-REC|TRI-DAI',
        cost: 45,	skill: 'SCT_OBT_3',
    },
];
