var HORNS = [
    {
        code: 'UGN_AMR',    name: "Divine Armor Umgarna",
        type: ARMOR,        material: HORN,
        score: 2278,        slots: 'DFS_4-QUI_5-CMB_4-DAI-KIT|TRI',
        cost: 35,
    },
    {
        code: 'DVN_PDG',    name: "Divine Pendragon",
        type: HEAD,         material: HORN,
        score: 4095,        slots: 'DFS_4-COU_5-SKL_4-CIR-TRI|CIR',
        cost: 35,
    },
    {
        code: 'MNG_VST',    name: "Vest of Managarmr",
        type: ARMOR,        material: HORN,
        score: 2613,        slots: 'DVR_5-FIRD_10-HAS_9-CIR-KIT|DAI',
        limited: true,      cost: 40,
    },
    {
        code: 'MNG_HPC',    name: "Headpiece of Managarmr",
        type: HEAD,         material: HORN,
        score: 4661,        slots: 'DVR_5-FIRD_10-CMB_9-DAI-TRI|CIR',
        limited: true,      cost: 40,
    },
    {
        code: 'REG_HNS',    name: "Regalia Harness",
        type: ARMOR,        material: HORN,
        score: 2168,        slots: 'SBK_4-HAS_5-QUI_3-KIT-TRI|TRI',
        cost: 34,
    },
    {
        code: 'REG_HLM',    name: "Regalia Helm",
        type: HEAD,         material: HORN,
        score: 4042,        slots: 'SBK_4-HEA_5-CIR-DAI-TRI|CIR',
        cost: 34,
    },
    {
        code: 'GIG_AMR',    name: "Gigas Armor",
        type: ARMOR,        material: HORN,
        score: 2131,        slots: 'RTB_4-COU_5-HAS_3-TRI-TRI|TRI',
        cost: 34,
    },
    {
        code: 'GIG_HPC',    name: "Gigas Headpiece",
        type: HEAD,         material: HORN,
        score: 3932,        slots: 'RTB_4-CMB_5-HEA_3-TRI-TRI|TRI',
        cost: 34,
    },
    {
        code: 'SIE_DMR',    name: "Dragon Armor Siegfried",
        type: ARMOR,        material: HORN,
        score: 2415,        slots: 'ICED_5-HEA_4-CIR-TRI-REC|DAI',
        limited: true,      cost: 36,
    },
    {
        code: 'BRA_DHM',    name: "Dragon Helm Bramdgride",
        type: HEAD,         material: HORN,
        score: 4160,        slots: 'ICED_5-SKL_3-SKL_3-DAI-TRI|CIR',
        limited: true,      cost: 36,
    },
    {
        code: 'GEO_PLT',    name: "Divine Georgios Plate",
        type: ARMOR,        material: HORN,
        score: 2092,        slots: 'RTB_4-CMB_3-CMB_3-CIR-REC|TRI',
        cost: 34,
    },
    {
        code: 'BZP_DGN',    name: "Divine Blazepen Dragon",
        type: HEAD,         material: HORN,
        score: 3842,        slots: 'RTB_4-ATK_3-ATK_3-DAI-TRI|TRI',
        cost: 34,
    },
    {
        code: 'SLY_COA',    name: "Deity Slayer Coat",
        type: ARMOR,        material: HORN,
        score: 2417,        slots: 'RTB_5-HAS_5-TRI-CIR-TRI|CIR',
        cost: 36,
    },
    {
        code: 'SLY_DIO',    name: "Holy Dio Slayer",
        type: HEAD,         material: HORN,
        score: 4245,        slots: 'RTB_5-CMB_5-CIR-DAI-TRI|TRI',
        cost: 36,
    },
    {
        code: '9999',    name: "Cobalt Crown",
        type: HEAD,         material: HORN,
        score: 4002,        slots: 'RTB_2-FIRD_4-HP_5-TRI-CIR',
        evt: true,          cost: 28,
    },
    {
        code: '9999',    name: "Cerulean Sea Mail",
        type: ARMOR,        material: HORN,
        score: 1325,        slots: 'RTB_2-FIRD_4-DEF_5-CIR-TRI',
        evt: true,          cost: 28,
    },
    {
        code: 'PLM_PDG',    name: "Pure Luminous Pendragon+",
        type: HEAD,         material: HORN,
        score: 4002,        slots: 'RTB_4-LHTD_5-EFR_3-CIR-REC|CIR',
        evt: true,          cost: 37,
    },
    {
        code: 'PPT_ART',    name: "Pure Photon Arts+",
        type: ARMOR,        material: HORN,
        score: 2365,        slots: 'DFS_4-LHTD_5-FUR_5-DEF_9-TRI|CIR',
        evt: true,          cost: 37,
    },
    {
        code: 'PLM_PDG',    name: "Pure Luminous Pendragon",
        type: HEAD,         material: HORN,
        score: 3776,        slots: 'RTB_4-LHTD_5-ELF_5-CIR-REC|CIR',
        evt: true,          cost: 32,
    },
    {
        code: 'PPT_ART',    name: "Pure Photon Arts",
        type: ARMOR,        material: HORN,
        score: 2131,        slots: 'DFS_4-LHTD_5-FUR_5-CIR-TRI|CIR',
        evt: true,          cost: 32,
    },
    {
        code: 'IMC_HEL',    name: "Immaculate Helmet",
        type: HEAD,         material: HORN,
        score: 4205,        slots: 'SBK_5-CMB_9-COU_5-CIR-DAI|TRI',
        cost: 37,
    },
    {
        code: 'IMC_AMR',    name: "Immaculate Armor",
        type: ARMOR,        material: HORN,
        score: 2354,        slots: 'SBK_5-HEA_9-SUR_5-CIR-TRI|CIR',
        cost: 37,
    },
    {
        code: 'INT_CPL',    name: "Immortal Ninetail Chaplet",
        type: HEAD,         material: HORN,
        score: 4768,        slots: 'LSG_5-KOH_5-SRS_5-TRI-REC|CIR-REC',
        limited: true,      cost: 50,
    },
    {
        code: 'INT_CLC',    name: "Immortal Ninetail Calico",
        type: ARMOR,        material: HORN,
        score: 2636,        slots: 'LSG_5-EFR_5-SPB_4-CIR-TRI|KIT-CIR',
        limited: true,      cost: 50,
    },
    {
        code: 'AGD_FHG',    name: "Aero-God Fuujin's Headgear",
        type: HEAD,         material: HORN,
        score: 3333,        slots: 'SBK_4-WNDD_5-ATK_9-TRI-CIR',
        evt: true,          cost: 33,
        brave_rate: 2,
    },
    {
        code: 'AGD_SUI',    name: "Aero-God Fuujin's Suit",
        type: ARMOR,        material: HORN,
        score: 2100,        slots: 'SBK_4-WNDD_5-DEF_9-REC-CIR',
        evt: true,          cost: 33,
        brave_rate: 2,
    },
    {
        code: 'EGD_FHG',    name: "Electro-God Raijin's Headgear",
        type: HEAD,         material: HORN,
        score: 3333,        slots: 'SBK_4-ELED_5-ATK_9-TRI-CIR',
        evt: true,          cost: 33,
        brave_rate: 2,
    },
    {
        code: 'EGD_SUI',    name: "Electro-God Raijin's Suit",
        type: ARMOR,        material: HORN,
        score: 2100,        slots: 'SBK_4-ELED_5-DEF_9-REC-CIR',
        evt: true,          cost: 33,
        brave_rate: 2,
    },
    {
        rcode: 3074,        name: "Silver Imperial Helm",
        type: HEAD,         material: HORN,
        score: 4380,        slots: 'WSM_5-HEA_9-SPB_5-TRI-CIR|TRI',
        cost: 36,
    },
    {
        rcode: 3074,        name: "Silver Imperial Mail",
        type: ARMOR,        material: HORN,
        score: 2510,        slots: 'WSM_5-CMB_10-KOH_4-TRI-REC|DAI',
        cost: 36,
    },
    {
        rcode: 3077,        name: "Pure Dragon Wyrm Helmet",
        type: HEAD,         material: HORN,
        score: 4313,        slots: 'DFS_4-ICED_5-WNDD_5-DAI-CIR|DAI',
        cost: 42,           evt: true,
    },
    {
        rcode: 3077,        name: "Pure Dragon Wyrm Mail",
        type: ARMOR,        material: HORN,
        score: 2411,        slots: 'DFS_4-ICED_5-WNDD_5-REC-DAI|DAI',
        cost: 42,           evt: true,
    },
    {
        rcode: 3082,        name: "Onyx Corps Beret",
        type: HEAD,         material: HORN,
        score: 4740,        slots: 'LSG_5-TMV_5-EFR_5-TRI-DAI|TRI',
        cost: 50,
    },
    {
        rcode: 3082,        name: "Coat of the Onyx Corps",
        type: ARMOR,        material: HORN,
        score: 2630,        slots: 'LSG_5-TMV_5-KOH_5-CIR-REC|KIT-REC',
        cost: 50,
    },
    {
        rcode: 9020,        name: "Crown of the Righteous",
        type: HEAD,         material: HORN,
        score: 4400,        slots: 'DFS_4-DRKD_5-ADH_4-TRI-REC',
        cost: 25,            evt: true,
    },
    {
        rcode: 9020,        name: "Divine Aegis",
        type: ARMOR,        material: HORN,
        score: 2420,        slots: 'DFS_4-DRKD_5-VSP_4-CIR-KIT',
        cost: 25,            evt: true,
    },
    {
        rcode: 3084,        name: "Dark Necromancer's Circlet",
        type: HEAD,         material: HORN,
        score: 4806,        slots: 'HKM_5-HEA_10-HWL_5-CIR-DAI|REC-REC',
        cost: 42,
    },
    {
        rcode: 3084,        name: "Black Necromancer's Robe",
        type: ARMOR,        material: HORN,
        score: 2690,        slots: 'HKM_5-MGR_5-TMV_5-CIR-TRI|KIT-DAI',
        cost: 42,
    },
    {
        rcode: 3091,        name: "Helm of the Vanquisher",
        type: HEAD,         material: HORN,
        score: 4850,        slots: 'GOO_5-TMV_6-MGR_5-CIR-KIT|TRI',
        cost: 42,
    },
    {
        rcode: 3091,        name: "Mail of the Vanquisher",
        type: ARMOR,        material: HORN,
        score: 2740,        slots: 'GOO_5-KOH_6-HEA_10-TRI-REC|REC-CIR',
        cost: 42,
    },
    {
        rcode: 3097,        name: "Flamme Casque en Rouge",
        type: HEAD,         material: HORN,
        score: 4900,        slots: 'HKM_5-HRF_6-SCT_5-DAI-REC|CIR-TRI',
        cost: 42,
    },
    {
        rcode: 3097,        name: "Flamme Armure en Rouge",
        type: ARMOR,        material: HORN,
        score: 2820,        slots: 'HKM_5-EFR_6-SPB_5-CIR-KIT|CIR-TRI',
        cost: 42,
    },
    {
        rcode: 9024,        name: "Hades's Hellfire Helm",
        type: HEAD,         material: HORN,
        score: 4704,        slots: 'AVG_4-ATK_10-ASC_5-TRI-CIR',
        cost: 42,           evt: true,
    },
    {
        rcode: 9024,        name: "Hades's Hellfire Mail",
        type: ARMOR,        material: HORN,
        score: 2670,        slots: 'AVG_4-ICED_5-BAR_5-CIR-REC|TRI-CIR',
        cost: 42,           evt: true,
        skill: 'ICE_BST_1',
    },
    {
        rcode: 3071,        name: "Apollon's Lyrical Helm",
        type: HEAD,         material: HORN,
        score: 3840,        slots: 'LSG_5-SCT_4-SPB_4-CIR-TRI|CIR',
        cost: 42,           evt: true,
        brave_rate: 2,
    },
    {
        rcode: 3071,        name: "Apollon's Epic Mail",
        type: ARMOR,        material: HORN,
        score: 2230,        slots: 'LSG_5-LHTD_5-WLW_4-CIR-REC|KIT',
        cost: 42,           evt: true,
        brave_rate: 2,      skill: 'PHT_CNN_3',
    },
    {
        rcode: 3101,        name: "Fangs of Fafnir",
        type: HEAD,         material: HORN,
        score: 5000,        slots: 'DVS_5-HWL_6-HEA_10-DAI-TRI|REC-CIR',
        cost: 45,
    },
    {
        rcode: 3101,        name: "Scale of Fafnir",
        type: ARMOR,        material: HORN,
        score: 2940,        slots: 'DVS_5-MGR_6-TMV_5-CIR-DAI|TRI-CIR',
        cost: 45,           skill: 'CHO_MTO_3',
    },
    {
        rcode: 3088,        name: "Red Riding Hood",
        type: HEAD,         material: HORN,
        score: 4540,        slots: 'SBK_5-SOG_5-QHT_5-CIR-TRI',
        cost: 45,            evt: true,
        name2: 'Big Bad Wolf Mouth',
    },
    {
        rcode: 3088,        name: "Hooded Hunter's Dress",
        type: ARMOR,        material: HORN,
        score: 2650,        slots: 'SBK_5-SSL_5-DSM_5-CIR-TRI|CIR-REC',
        cost: 45,            evt: true,
        name2: "Wolf Master's Mail",
        skill: 'BLZ_OBT_3',
    },
    // 2015-10-30
    {
        rcode: 3116,        name: "Halloween Trickster Hat",
        type: HEAD,         material: HORN,
        score: 5320,        slots: 'DVS_6-HWL_5-EFR_6-HAS_10-KIT|CIR-REC',
        cost: 50,
    },
    {
        rcode: 3116,        name: "Halloween Trickster Robe",
        type: ARMOR,        material: HORN,
        score: 3350,        slots: 'DVS_6-MGR_6-KOH_5-HEA_10-DAI|TRI-TRI',
        cost: 50,            skill: 'FRZ_OBT_3',
    },
];
