var IRONS = [
    {
        code: 'DFM_GRB',    name: "Divine Fuma Ninja Garb",
        type: ARMOR,        material: IRON,
        score: 2129,        slots: 'BIA_4-HAS_5-SKL_5-CIR-KIT|TRI',
        cost: 34,
    },
    {
        code: 'DFM_HOD',    name: "Divine Fuma Hood",
        type: HEAD,         material: IRON,
        score: 3909,        slots: 'BIA_4-SKA_4-TRI-CIR-TRI|CIR',
        cost: 34,
    },
    {
        code: 'EST_AMR',    name: "Esoteric Armor",
        type: ARMOR,        material: IRON,
        score: 2119,        slots: 'ABS_4-HEA_5-HP_4-REC-CIR|CIR',
        cost: 34,
    },
    {
        code: 'EST_BND',    name: "Esoteric Band",
        type: HEAD,         material: IRON,
        score: 3919,        slots: 'ABS_4-CMB_5-SKL_5-KIT-CIR|TRI',
        cost: 34,
    }, 
    {
        code: 'VAL_AMR',    name: "Valor Armor",
        type: ARMOR,        material: IRON,
        score: 2196,        slots: 'BIA_4-SKL_5-HEA_3-REC-TRI|TRI',
        cost: 34,
    },
    {
        code: 'VAL_HLM',    name: "Valor Helm",
        type: HEAD,         material: IRON,
        score: 4031,        slots: 'BIA_4-CMB_5-SKG_4-TRI-CIR|TRI',
        cost: 34,
    },
    {
        code: 'CSD_AMR',    name: "Crusader Armor",
        type: ARMOR,        material: IRON,
        score: 2158,        slots: 'SBI_4-HAS_5-TRI-KIT-CIR|CIR',
        cost: 34,
    },
    {
        code: 'CSD_HLM',    name: "Crusader Helm",
        type: HEAD,         material: IRON,
        score: 3960,        slots: 'SBI_4-SKL_5-DAI-CIR-TRI|CIR',
        cost: 34,
    },
    {
        code: 'VRG_CRW',    name: "Vierge Crown",
        type: HEAD,         material: IRON,
        score: 4220,        slots: 'BIA_5-SKL_5-CMB_5-TRI-DAI|DAI',
        cost: 36,
    },
    {
        code: 'SKA_VRG',    name: "Spirit King Armor of Vierge",
        type: ARMOR,        material: IRON,
        score: 2352,        slots: 'BIA_5-HEA_4-HAS_5-TRI-TRI|TRI',
        cost: 36,
    },
    {
        code: 'EQS_MAI',    name: "Eternal Queenslayer's Mail",
        type: ARMOR,        material: IRON,
        score: 2360,        slots: 'SBI_5-QUI_9-ATK_10-TRI-CIR|TRI',
        cost: 37,
    },
    {
        code: 'EQS_HLM',    name: "Eternal Queenslayer's Helm",
        type: HEAD,         material: IRON,
        score: 4249,        slots: 'SBI_5-HEA_9-HP_10-TRI-TRI|CIR',
        cost: 37,
    },
    {
        code: 'EQT_AMR',    name: "Armor of Equitatus+",
        type: ARMOR,        material: IRON,
        score: 2415,        slots: 'LSG_4-ELED_5-HEA_9-CIR-DAI|CIR',
        evt: true,          cost: 37,
    },
    {
        code: 'HMT_GLR',    name: "Helmet of Gloria",
        type: HEAD,         material: IRON,
        score: 3806,        slots: 'LSG_4-DRKD_5-SPS_4-CIR-TRI',
        evt: true,          cost: 32,
    },
    {
        code: 'HMT_GLR',    name: "Helmet of Gloria+",
        type: HEAD,         material: IRON,
        score: 4337,        slots: 'LSG_4-DRKD_5-SRS_3-CIR-TRI',
        evt: true,          cost: 37,
    },
    {
        code: '9999',    name: "Armor of Sanctus",
        type: ARMOR,        material: IRON,
        score: 2161,        slots: 'LSG_4-ELED_5-HEA_8-CIR-DAI',
        evt: true,      cost: 32,
    },
    {
        code: '9999',    name: "Armor of Sanctus+",
        type: ARMOR,        material: IRON,
        score: 2415,        slots: 'LSG_4-ELED_5-HEA_9-CIR-DAI',
        evt: true,      cost: 37,
    },
    {
        code: 'HWM_HAT',    name: "Heart-Warming Hat",
        type: HEAD,         material: IRON,
        score: 4643,        slots: 'LSG_5-KOH_5-SKA_9-TRI-KIT|CIR',
        limited: true,      cost: 40,
    },
    {
        code: 'GWN_ACR',    name: "Gown of Angelic Charity",
        type: ARMOR,        material: IRON,
        score: 2606,        slots: 'LSG_5-ADH_5-QUI_9-TRI-REC|TRI',
        limited: true,      cost: 40,
    },
    {
        code: 'HLM_DBK',    name: "Helm of the Dawn Breaker",
        type: HEAD,         material: IRON,
        score: 4628,        slots: 'DVR_5-SRS_5-HEA_10-CIR-TRI|CIR',
        limited: true,      cost: 40,
    },
    {
        code: 'MAI_DBK',    name: "Mail of the Dawn Breaker",
        type: ARMOR,        material: IRON,
        score: 2581,        slots: 'DVR_5-KOH_5-QUI_10-TRI-CIR|TRI',
        limited: true,      cost: 40,
    },
    {
        code: 'CDB_HLM',    name: "Cursed Diabolos Helm",
        type: HEAD,         material: IRON,
        score: 4708,        slots: 'GOO_5-HEA_10-SKA_10-CIR-TRI|CIR',
        limited: true,      cost: 50,
    },
    {
        code: 'CDB_MAI',    name: "Cursed Diabolos Mail",
        type: ARMOR,        material: IRON,
        score: 2600,        slots: 'GOO_5-QUI_9-EFR_5-CIR-KIT|TRI',
        limited: true,      cost: 50,
    },
    {
        code: 'SHV_HLM',    name: "Sixth-Heaven Archdemon Helm",
        type: HEAD,         material: IRON,
        score: 3864,        slots: 'ABS_4-DRKD_5-DEF_10-TRI-TRI|CIR',
        evt: true,          cost: 34,
    },
    {
        code: 'SHV_MAI',    name: "Sixth-Heaven Archdemon Mail",
        type: ARMOR,        material: IRON,
        score: 2158,        slots: 'ABS_4-DRKD_5-DEF_10-CIR-REC',
        evt: true,          cost: 34,
    },
    {
        code: 'DEX_MMA',    name: "Deus ex Machina Mail",
        type: ARMOR,        material: IRON,
        score: 2500,        slots: 'AVG_5-HEA_10-KOH_4-REC-TRI|CIR',
        cost: 37,
    },
    {
        code: 'DEX_MHE',    name: "Deus ex Machina Helm",
        type: HEAD,         material: IRON,
        score: 4370,        slots: 'AVG_5-SKL_10-ADH_4-DAI-KIT|CIR',
        cost: 37,
    },
    {
        code: 'SCT_HGR',    name: "Sky Captain's Headgear",
        type: HEAD,         material: IRON,
        score: 4377,        slots: 'DVR_5-QUI_9-KOH_5-DAI-TRI|TRI',
        cost: 37,
    },
    {
        code: 'SCT_GEA',    name: "Sky Captain's Gear",
        type: ARMOR,        material: IRON,
        score: 2507,        slots: 'DVR_5-HEA_9-SRS_5-REC-TRI|CIR',
        cost: 37,
    },
    {
        rcode: 3075,        name: "Crescent Dragon Knight",
        type: HEAD,         material: IRON,
        score: 4775,        slots: 'LSG_5-EFR_5-KOH_5-KIT-KIT|REC',
        limited: true,      cost: 48,
    },
    {
        rcode: 3075,        name: "Celestial Dragon Knight",
        type: ARMOR,        material: IRON,
        score: 2775,        slots: 'LSG_5-EFR_5-SPB_5-DAI-REC|TRI-TRI',
        limited: true,      cost: 48,
    },
    {
        rcode: 9019,        name: "Ace of Spades",
        type: ARMOR,        material: IRON,
        score: 2380,        slots: 'BIA_4-QUI_9-STD_5-CIR-TRI|CIR',
        evt: true,          cost: 22,
    },
    {
        rcode: 3078,        name: "High Roller's Red Dog Circlet",
        type: HEAD,         material: IRON,
        score: 4547,        slots: 'DVR_5-SPB_4-KOH_5-TRI-REC|TRI',
        cost: 42,
    },
    {
        rcode: 3078,        name: "High Roller's Blackjack Suit",
        type: ARMOR,        material: IRON,
        score: 2540,        slots: 'DVR_5-HEA_10-HRF_4-TRI-DAI|REC',
        cost: 42,            skill:'BLZ_OBT_3'
    },
    {
        rcode: 3076,        name: "Lucifer's Fallen Helm",
        type: HEAD,         material: IRON,
        score: 4700,        slots: 'AVG_5-MGR_5-SPB_5-TRI-TRI|REC-CIR',
        cost: 45,
    },
    {
        rcode: 3076,        name: "Lucifer's Fallen Mail",
        type: ARMOR,        material: IRON,
        score: 2590,        slots: 'AVG_5-MGR_5-HTF_5-KIT-TRI|CIR-TRI',
        cost: 42,           skill:'CHO_MTO_3'
    },
    {
        rcode: 3063,        name: "Headset of the Seeker",
        type: HEAD,         material: IRON,
        score: 4930,        slots: 'STB_6-EFR_5-SPB_5-CIR-REC|DAI-DAI',
        cost: 50,           limited: true,
    },
    {
        rcode: 3063,        name: "Coat of the Seeker",
        type: ARMOR,        material: IRON,
        score: 2800,        slots: 'STB_6-TMV_5-HWL_5-CIR-DAI|TRI-TRI',
        cost: 50,           limited: true,
    },
    {
        rcode: 3069,        name: "Vice Helm of Guilt",
        type: HEAD,         material: IRON,
        score: 4466,        slots: 'BIA_5-HRF_4-SKA_9-TRI-CIR|CIR',
        cost: 42,           evt: true,
    },
    {
        rcode: 3069,        name: "Vice Mail of Guilt",
        type: ARMOR,        material: IRON,
        score: 2447,        slots: 'BIA_5-SPB_4-HEA_9-DAI-CIR|TRI',
        cost: 42,           evt: true,
    },
    {
        rcode: 30692,       name: "Vice Helm of Guilt+",
        type: HEAD,         material: IRON,
        score: 4500,        slots: 'BIA_5-SPB_4-HEA_9-DAI-CIR|CIR',
        cost: 42,           evt: true,
    },
    {
        rcode: 30692,       name: "Vice Mail of Guilt+",
        type: ARMOR,        material: IRON,
        score: 2460,        slots: 'BIA_5-SPB_4-HEA_9-DAI-CIR|TRI',
        cost: 42,           evt: true,
        skill: 'PHT_CNN_1',
    },
    {
        rcode: 9022,        name: "Helm of the Royal Guard",
        type: HEAD,         material: IRON,
        score: 4480,        slots: 'ICED_5-VSP_5-ABS_5-CIR-DAI',
        cost: 0,            evt: true,
    },
    {
        rcode: 9022,        name: "Plate of the Royal Guard",
        type: ARMOR,        material: IRON,
        score: 2460,        slots: 'ICED_5-DSM_4-HEA_10-CIR-REC',
        cost: 0,            evt: true,
    },
    {
        rcode: 9016,        name: "Helm of Valhalla",
        type: HEAD,         material: IRON,
        score: 5000,        slots: 'WSM_6-HEA_10-WLW_6-TRI-CIR|DAI-TRI',
        cost: 50,           limited: true,
    },
    {
        rcode: 9016,        name: "Valhalla Mail",
        type: ARMOR,        material: IRON,
        score: 2950,        slots: 'WSM_6-SPB_5-TMV_6-TRI-CIR|DAI-REC',
        cost: 50,           limited: true,
    },
    {
        rcode: 3099,        name: "Gallium Celeste",
        type: HEAD,         material: IRON,
        score: 4920,        slots: 'LSG_5-WLW_6-TMV_5-TRI-KIT|CIR-REC',
        cost: 45,
    },
    {
        rcode: 3099,        name: "Alma Celeste",
        type: ARMOR,        material: IRON,
        score: 2850,        slots: 'LSG_5-MGR_5-SOG_6-TRI-DAI|CIR-REC',
        cost: 45,           skill: 'ICE_BST_3',
    },
    {
        rcode: 3095,        name: "Lethal Artillery Cap",
        type: HEAD,         material: IRON,
        score: 5060,        slots: 'DVS_5-TMV_6-MGR_5-TRI-KIT|TRI-CIR',
        cost: 45,
    },
    {
        rcode: 3095,        name: "Lethal Artillery Vest",
        type: ARMOR,        material: IRON,
        score: 3050,        slots: 'DVS_5-MGR_6-SPB_5-KIT-REC|TRI-CIR',
        cost: 45,            skill: 'CHO_MTO_3',
    },
    // 2015-10-09
    {
        rcode: 3113,        name: "Shadow Knight's Helm",
        type: HEAD,         material: IRON,
        score: 5110,        slots: 'LSG_5-KOH_6-HRF_5-SKG_10-TRI|CIR-REC',
        cost: 45,
    },
    {
        rcode: 3113,        name: "Shadow Knight's Mail",
        type: ARMOR,        material: IRON,
        score: 3130,        slots: 'LSG_5-KOH_6-SPB_5-HEA_10-TRI|DAI-TRI',
        cost: 45,            skill: 'SHD_OBT_3',
    },
];
