var SLOTS = {
    // status boost
    'ATK_1'  : { type: CIR, title: 'Attacker Lv.1', desc: 'ATK +3%', },
    'ATK_2'  : { type: CIR, title: 'Attacker Lv.2', desc: 'ATK +5%', },
    'ATK_3'  : { type: CIR, title: 'Attacker Lv.3', desc: 'ATK +7%', },
    'ATK_4'  : { type: CIR, title: 'Attacker Lv.4', desc: 'ATK +10%', },
    'ATK_5'  : { type: CIR, title: 'Attacker Lv.5', desc: 'ATK +15%', },
    'ATK_6'  : { type: CIR, title: 'Attack Boost Lv.1', desc: 'ATK +10%', },
    'ATK_7'  : { type: CIR, title: 'Attack Boost Lv.2', desc: 'ATK +15%', },
    'ATK_8'  : { type: CIR, title: 'Attack Boost Lv.3', desc: 'ATK +20%', },
    'ATK_9'  : { type: CIR, title: 'Attack Boost Lv.4', desc: 'ATK +25%', },
    'ATK_10' : { type: CIR, title: 'Attack Boost Lv.5', desc: 'ATK +30%', },
    
    'DEF_1'  : { type: CIR, title: 'Defender Lv.1', desc: 'DEF +3%', },
    'DEF_2'  : { type: CIR, title: 'Defender Lv.2', desc: 'DEF +5%', },
    'DEF_3'  : { type: CIR, title: 'Defender Lv.3', desc: 'DEF +7%', },
    'DEF_4'  : { type: CIR, title: 'Defender Lv.4', desc: 'DEF +10%', },
    'DEF_5'  : { type: CIR, title: 'Defender Lv.5', desc: 'DEF +15%', },
    'DEF_6'  : { type: CIR, title: 'Defender Boost Lv.1', desc: 'DEF +10%', },
    'DEF_7'  : { type: CIR, title: 'Defender Boost Lv.2', desc: 'DEF +15%', },
    'DEF_8'  : { type: CIR, title: 'Defender Boost Lv.3', desc: 'DEF +20%', },
    'DEF_9'  : { type: CIR, title: 'Defender Boost Lv.4', desc: 'DEF +25%', },
    'DEF_10' : { type: CIR, title: 'Defender Boost Lv.5', desc: 'DEF +30%', },

    'HP_1'   : { type: CIR, title: 'HP Boost Lv.1', desc: 'HP +3%', },
    'HP_2'   : { type: CIR, title: 'HP Boost Lv.2', desc: 'HP +5%', },
    'HP_3'   : { type: CIR, title: 'HP Boost Lv.3', desc: 'HP +7%', },
    'HP_4'   : { type: CIR, title: 'HP Boost Lv.4', desc: 'HP +10%', },
    'HP_5'   : { type: CIR, title: 'HP Boost Lv.5', desc: 'HP +15%', },
    'HP_6'   : { type: CIR, title: 'HP Gain Lv.1',  desc: 'HP +10%', },
    'HP_7'   : { type: CIR, title: 'HP Gain Lv.2',  desc: 'HP +15%', },
    'HP_8'   : { type: CIR, title: 'HP Gain Lv.3',  desc: 'HP +20%', },
    'HP_9'   : { type: CIR, title: 'HP Gain Lv.4',  desc: 'HP +25%', },
    'HP_10'  : { type: CIR, title: 'HP Gain Lv.5',  desc: 'HP +30%', },

    'SRS_1'  : { type: CIR, title: "Serrated Shield Lv.1", desc: 'ATK, DEF +10%', },
    'SRS_2'  : { type: CIR, title: "Serrated Shield Lv.2", desc: 'ATK, DEF +15%', },
    'SRS_3'  : { type: CIR, title: "Serrated Shield Lv.3", desc: 'ATK, DEF +20%', },
    'SRS_4'  : { type: CIR, title: "Serrated Shield Lv.4", desc: 'ATK, DEF +25%', },
    'SRS_5'  : { type: CIR, title: "Serrated Shield Lv.5", desc: 'ATK, DEF +30%', },

    'SPS_1'  : { type: CIR, title: "Sharpended Shield Lv.1", desc: 'ATK, DEF +3%', },
    'SPS_2'  : { type: CIR, title: "Sharpended Shield Lv.2", desc: 'ATK, DEF +5%', },
    'SPS_3'  : { type: CIR, title: "Sharpended Shield Lv.3", desc: 'ATK, DEF +7%', },
    'SPS_4'  : { type: CIR, title: "Sharpended Shield Lv.4", desc: 'ATK, DEF +10%', },
    'SPS_5'  : { type: CIR, title: "Sharpended Shield Lv.5", desc: 'ATK, DEF +15%', },

    'HVH_1'  : { type: CIR, title: "Heavy Hitter Lv.1", desc: 'ATK, HP +3%', },
    'HVH_2'  : { type: CIR, title: "Heavy Hitter Lv.2", desc: 'ATK, HP +5%', },
    'HVH_3'  : { type: CIR, title: "Heavy Hitter Lv.3", desc: 'ATK, HP +7%', },
    'HVH_4'  : { type: CIR, title: "Heavy Hitter Lv.4", desc: 'ATK, HP +10%', },
    'HVH_5'  : { type: CIR, title: "Heavy Hitter Lv.5", desc: 'ATK, HP +15%', },

    'KOH_1'  : { type: CIR, title: "Knockout Hitter Lv.1", desc: 'ATK, HP +10%', },
    'KOH_2'  : { type: CIR, title: "Knockout Hitter Lv.2", desc: 'ATK, HP +15%', },
    'KOH_3'  : { type: CIR, title: "Knockout Hitter Lv.3", desc: 'ATK, HP +20%', },
    'KOH_4'  : { type: CIR, title: "Knockout Hitter Lv.4", desc: 'ATK, HP +25%', },
    'KOH_5'  : { type: CIR, title: "Knockout Hitter Lv.5", desc: 'ATK, HP +30%', },
    'KOH_6'  : { type: CIR, title: "Knockout Hitter Lv.6", desc: 'ATK, HP +40%', },

    'DMH_1'  : { type: CIR, title: "Diamondhide Lv.1",     desc: 'DEF, HP +3%', },
    'DMH_2'  : { type: CIR, title: "Diamondhide Lv.2",     desc: 'DEF, HP +5%', },
    'DMH_3'  : { type: CIR, title: "Diamondhide Lv.3",     desc: 'DEF, HP +7%', },
    'DMH_4'  : { type: CIR, title: "Diamondhide Lv.4",     desc: 'DEF, HP +10%', },
    'DMH_5'  : { type: CIR, title: "Diamondhide Lv.5",     desc: 'DEF, HP +15%', },

    'ADH_1'  : { type: CIR, title: "Adamantine Hide Lv.1", desc: 'DEF, HP +10%', },
    'ADH_2'  : { type: CIR, title: "Adamantine Hide Lv.2", desc: 'DEF, HP +15%', },
    'ADH_3'  : { type: CIR, title: "Adamantine Hide Lv.3", desc: 'DEF, HP +20%', },
    'ADH_4'  : { type: CIR, title: "Adamantine Hide Lv.4", desc: 'DEF, HP +25%', },
    'ADH_5'  : { type: CIR, title: "Adamantine Hide Lv.5", desc: 'DEF, HP +30%', },

    // damage boost
    'CMB_1'  : { type: TRI, title: 'Combo Attacker Lv.1', desc: 'Combo DMG +5%', },
    'CMB_2'  : { type: TRI, title: 'Combo Attacker Lv.2', desc: 'Combo DMG +10%', },
    'CMB_3'  : { type: TRI, title: 'Combo Attacker Lv.3', desc: 'Combo DMG +15%', },
    'CMB_4'  : { type: TRI, title: 'Combo Attacker Lv.4', desc: 'Combo DMG +25%', },
    'CMB_5'  : { type: TRI, title: 'Combo Attacker Lv.5', desc: 'Combo DMG +35%', },
    'CMB_6'  : { type: TRI, title: 'Combo Damage Boost Lv.1', desc: 'Combo DMG +25%', },
    'CMB_7'  : { type: TRI, title: 'Combo Damage Boost Lv.2', desc: 'Combo DMG +35%', },
    'CMB_8'  : { type: TRI, title: 'Combo Damage Boost Lv.3', desc: 'Combo DMG +45%', },
    'CMB_9'  : { type: TRI, title: 'Combo Damage Boost Lv.4', desc: 'Combo DMG +55%', },
    'CMB_10' : { type: TRI, title: 'Combo Damage Boost Lv.5', desc: 'Combo DMG +65%', },

    'SKL_1'  : { type: TRI, title: 'Skill Enhancer Lv.1', desc: 'Skill DMG +5%', },
    'SKL_2'  : { type: TRI, title: 'Skill Enhancer Lv.2', desc: 'Skill DMG +10%', },
    'SKL_3'  : { type: TRI, title: 'Skill Enhancer Lv.3', desc: 'Skill DMG +15%', },
    'SKL_4'  : { type: TRI, title: 'Skill Enhancer Lv.4', desc: 'Skill DMG +25%', },
    'SKL_5'  : { type: TRI, title: 'Skill Enhancer Lv.5', desc: 'Skill DMG +35%', },
    'SKL_6'  : { type: TRI, title: 'Skill Damage Boost Lv.1', desc: 'Skill DMG +25%', },
    'SKL_7'  : { type: TRI, title: 'Skill Damage Boost Lv.2', desc: 'Skill DMG +35%', },
    'SKL_8'  : { type: TRI, title: 'Skill Damage Boost Lv.3', desc: 'Skill DMG +45%', },
    'SKL_9'  : { type: TRI, title: 'Skill Damage Boost Lv.4', desc: 'Skill DMG +55%', },
    'SKL_10' : { type: TRI, title: 'Skill Damage Boost Lv.5', desc: 'Skill DMG +65%', },

    'ELF_1'  : { type: TRI, title: "Elite Force Lv.1", desc: 'Skill, Combo DMG +5%', },
    'ELF_2'  : { type: TRI, title: "Elite Force Lv.2", desc: 'Skill, Combo DMG +10%', },
    'ELF_3'  : { type: TRI, title: "Elite Force Lv.3", desc: 'Skill, Combo DMG +15%', },
    'ELF_4'  : { type: TRI, title: "Elite Force Lv.4", desc: 'Skill, Combo DMG +25%', },
    'ELF_5'  : { type: TRI, title: "Elite Force Lv.5", desc: 'Skill, Combo DMG +35%', },

    'EFR_1'  : { type: TRI, title: "Elite Fury Lv.1", desc: 'Skill, Combo DMG +25%', },
    'EFR_2'  : { type: TRI, title: "Elite Fury Lv.2", desc: 'Skill, Combo DMG +35%', },
    'EFR_3'  : { type: TRI, title: "Elite Fury Lv.3", desc: 'Skill, Combo DMG +45%', },
    'EFR_4'  : { type: TRI, title: "Elite Fury Lv.4", desc: 'Skill, Combo DMG +55%', },
    'EFR_5'  : { type: TRI, title: "Elite Fury Lv.5", desc: 'Skill, Combo DMG +65%', },
    'EFR_6'  : { type: TRI, title: "Elite Fury Lv.6", desc: 'Skill, Combo DMG +75%', },

    'MSM_1'  : { type: TRI, title: "Mage's Smash Lv.1", desc: 'Skill DMG +5%, ATK +3%', },
    'MSM_2'  : { type: TRI, title: "Mage's Smash Lv.2", desc: 'Skill DMG +10%, ATK +5%', },
    'MSM_3'  : { type: TRI, title: "Mage's Smash Lv.3", desc: 'Skill DMG +15%, ATK +7%', },
    'MSM_4'  : { type: TRI, title: "Mage's Smash Lv.4", desc: 'Skill DMG +20%, ATK +10%', },
    'MSM_5'  : { type: TRI, title: "Mage's Smash Lv.5", desc: 'Skill DMG +35%, ATK +15%', },

    'HWL_1'  : { type: TRI, title: 'Heart of the Warlock Lv.1', desc: 'Skill DMG +25%, ATK +10%', },
    'HWL_2'  : { type: TRI, title: 'Heart of the Warlock Lv.2', desc: 'Skill DMG +35%, ATK +15%', },
    'HWL_3'  : { type: TRI, title: 'Heart of the Warlock Lv.3', desc: 'Skill DMG +45%, ATK +20%', },
    'HWL_4'  : { type: TRI, title: 'Heart of the Warlock Lv.4', desc: 'Skill DMG +55%, ATK +25%', },
    'HWL_5'  : { type: TRI, title: 'Heart of the Warlock Lv.5', desc: 'Skill DMG +65%, ATK +30%', },
    'HWL_6'  : { type: TRI, title: 'Heart of the Warlock Lv.6', desc: 'Skill DMG +75%, ATK +45%', },

    'BAR_1'  : { type: TRI, title: "Brawler's Aura Lv.1", desc: 'Combo DMG +5%, ATK +3%', },
    'BAR_2'  : { type: TRI, title: "Brawler's Aura Lv.2", desc: 'Combo DMG +10%, ATK +5%', },
    'BAR_3'  : { type: TRI, title: "Brawler's Aura Lv.3", desc: 'Combo DMG +15%, ATK +7%', },
    'BAR_4'  : { type: TRI, title: "Brawler's Aura Lv.4", desc: 'Combo DMG +25%, ATK +10%', },
    'BAR_5'  : { type: TRI, title: "Brawler's Aura Lv.5", desc: 'Combo DMG +35%, ATK +15%', },

    'SOG_1'  : { type: TRI, title: 'Soul of the Gladiator Lv.1', desc: 'Combo DMG +30%, ATK +10%', },
    'SOG_2'  : { type: TRI, title: 'Soul of the Gladiator Lv.2', desc: 'Combo DMG +35%, ATK +15%', },
    'SOG_3'  : { type: TRI, title: 'Soul of the Gladiator Lv.3', desc: 'Combo DMG +45%, ATK +20%', },
    'SOG_4'  : { type: TRI, title: 'Soul of the Gladiator Lv.4', desc: 'Combo DMG +55%, ATK +25%', },
    'SOG_5'  : { type: TRI, title: 'Soul of the Gladiator Lv.5', desc: 'Combo DMG +65%, ATK +30%', },
    'SOG_6'  : { type: TRI, title: 'Soul of the Gladiator Lv.6', desc: 'Combo DMG +75%, ATK +45%', },

    'SPG_1'  : { type: TRI, title: 'Spark of the Gladiator Lv.1', desc: 'Combo DMG +30%, HP +10%', },
    'SPG_2'  : { type: TRI, title: 'Spark of the Gladiator Lv.2', desc: 'Combo DMG +35%, HP +15%', },
    'SPG_3'  : { type: TRI, title: 'Spark of the Gladiator Lv.3', desc: 'Combo DMG +45%, HP +20%', },
    'SPG_4'  : { type: TRI, title: 'Spark of the Gladiator Lv.4', desc: 'Combo DMG +55%, HP +25%', },
    'SPG_5'  : { type: TRI, title: 'Spark of the Gladiator Lv.5', desc: 'Combo DMG +65%, HP +30%', },
    'SPG_6'  : { type: TRI, title: 'Spark of the Gladiator Lv.6', desc: 'Combo DMG +75%, HP +40%', },

    // special type 1
    'HEA_1'  : { type: KIT, title: 'Auto Heal Lv.1', desc: 'Heal +3%', },
    'HEA_2'  : { type: KIT, title: 'Auto Heal Lv.2', desc: 'Heal +5%', },
    'HEA_3'  : { type: KIT, title: 'Auto Heal Lv.3', desc: 'Heal +7%', },
    'HEA_4'  : { type: KIT, title: 'Auto Heal Lv.4', desc: 'Heal +9%', },
    'HEA_5'  : { type: KIT, title: 'Auto Heal Lv.5', desc: 'Heal +11%', },
    'HEA_6'  : { type: KIT, title: 'Auto Recover Lv.1', desc: 'Heal +9%', },
    'HEA_7'  : { type: KIT, title: 'Auto Recover Lv.2', desc: 'Heal +11%', },
    'HEA_8'  : { type: KIT, title: 'Auto Recover Lv.3', desc: 'Heal +13%', },
    'HEA_9'  : { type: KIT, title: 'Auto Recover Lv.4', desc: 'Heal +15%', },
    'HEA_10' : { type: KIT, title: 'Auto Recover Lv.5', desc: 'Heal +17%', },

    'HAS_1'  : { type: REC, title: 'Haste Lv.1', desc: 'Distance +5%', },
    'HAS_2'  : { type: REC, title: 'Haste Lv.2', desc: 'Distance +10%', },
    'HAS_3'  : { type: REC, title: 'Haste Lv.3', desc: 'Distance +15%', },
    'HAS_4'  : { type: REC, title: 'Haste Lv.4', desc: 'Distance +20%', },
    'HAS_5'  : { type: REC, title: 'Haste Lv.5', desc: 'Distance +25%', },
    'HAS_6'  : { type: REC, title: 'Movement Boost Lv.1', desc: 'Distance +20%', },
    'HAS_7'  : { type: REC, title: 'Movement Boost Lv.2', desc: 'Distance +25%', },
    'HAS_8'  : { type: REC, title: 'Movement Boost Lv.3', desc: 'Distance +30%', },
    'HAS_9'  : { type: REC, title: 'Movement Boost Lv.4', desc: 'Distance +35%', },
    'HAS_10' : { type: REC, title: 'Movement Boost Lv.5', desc: 'Distance +40%', },

    'QUI_1'  : { type: REC, title: 'Quick Stance Lv.1', desc: 'Turn comes a little bit sooner', },
    'QUI_2'  : { type: REC, title: 'Quick Stance Lv.2', desc: 'Turn comes a little bit sooner', },
    'QUI_3'  : { type: REC, title: 'Quick Stance Lv.3', desc: 'Turn comes a bit sooner', },
    'QUI_4'  : { type: REC, title: 'Quick Stance Lv.4', desc: 'Turn comes sooner', },
    'QUI_5'  : { type: REC, title: 'Quick Stance Lv.5', desc: 'Turn comes much sooner', },
    'QUI_6'  : { type: REC, title: 'Quick Boost Lv.1', desc: 'Turn comes sooner', },
    'QUI_7'  : { type: REC, title: 'Quick Boost Lv.2', desc: 'Turn comes sooner', },
    'QUI_8'  : { type: REC, title: 'Quick Boost Lv.3', desc: 'Turn comes much sooner', },
    'QUI_9'  : { type: REC, title: 'Quick Boost Lv.4', desc: 'Turn comes massively quicker', },
    'QUI_10' : { type: REC, title: 'Quick Boost Lv.5', desc: 'Turn comes ludicrously quicker', },

    'ASM_1'  : { type: KIT, title: 'Assimilation Lv.1', desc: 'Absorb DMG as HP 1%', },
    'ASM_2'  : { type: KIT, title: 'Assimilation Lv.2', desc: 'Absorb DMG as HP 3%', },
    'ASM_3'  : { type: KIT, title: 'Assimilation Lv.3', desc: 'Absorb DMG as HP 5%', },
    'ASM_4'  : { type: KIT, title: 'Assimilation Lv.4', desc: 'Absorb DMG as HP 7%', },
    'ASM_5'  : { type: KIT, title: 'Assimilation Lv.5', desc: 'Absorb DMG as HP 10%', },

    'NBR_1'  : { type: REC, title: 'Nimble Resilience Lv.1', desc: 'Turn comes a little bit sooner, HP +3%', },
    'NBR_2'  : { type: REC, title: 'Nimble Resilience Lv.2', desc: 'Turn comes a little bit sooner, HP +5%', },
    'NBR_3'  : { type: REC, title: 'Nimble Resilience Lv.3', desc: 'Turn comes a bit sooner, HP +10%', },
    'NBR_4'  : { type: REC, title: 'Nimble Resilience Lv.4', desc: 'Turn comes sooner, HP +15%', },
    'NBR_5'  : { type: REC, title: 'Nimble Resilience Lv.5', desc: 'Turn comes much sooner, HP +20%', },

    'QHT_1'  : { type: REC, title: 'Quick Hitter Lv.1', desc: 'Turn comes a little bit sooner, ATK +3%', },
    'QHT_2'  : { type: REC, title: 'Quick Hitter Lv.2', desc: 'Turn comes a little bit sooner, ATK +5%', },
    'QHT_3'  : { type: REC, title: 'Quick Hitter Lv.3', desc: 'Turn comes a bit sooner, ATK +10%', },
    'QHT_4'  : { type: REC, title: 'Quick Hitter Lv.4', desc: 'Turn comes sooner, ATK +15%', },
    'QHT_5'  : { type: REC, title: 'Quick Hitter Lv.5', desc: 'Turn comes much sooner, ATK +20%', },

    'SPB_1'  : { type: REC, title: 'Spry Buster Lv.1', desc: 'Turn comes sooner, ATK +10%', },
    'SPB_2'  : { type: REC, title: 'Spry Buster Lv.2', desc: 'Turn comes sooner, ATK +15%', },
    'SPB_3'  : { type: REC, title: 'Spry Buster Lv.3', desc: 'Turn comes much sooner, ATK +20%', },
    'SPB_4'  : { type: REC, title: 'Spry Buster Lv.4', desc: 'Turn comes massively quicker, ATK +25%', },
    'SPB_5'  : { type: REC, title: 'Spry Buster Lv.5', desc: 'Turn comes ludicrously quicker, ATK +30%', },
    'SPB_6'  : { type: REC, title: 'Spry Buster Lv.6', desc: 'Turn comes ludicrously quicker, ATK +35%', },

    'STD_1'  : { type: REC, title: "Soothing Dash Lv.1", desc: 'HP, Distance +5%', },
    'STD_2'  : { type: REC, title: "Soothing Dash Lv.2", desc: 'HP, Distance +10%', },
    'STD_3'  : { type: REC, title: "Soothing Dash Lv.3", desc: 'HP, Distance +15%', },
    'STD_4'  : { type: REC, title: "Soothing Dash Lv.4", desc: 'HP, Distance +20%', },
    'STD_5'  : { type: REC, title: "Soothing Dash Lv.5", desc: 'HP, Distance +25%', },

    'HTF_1'  : { type: REC, title: "Hunter's Focus Lv.1", desc: 'HP, Distance +20%', },
    'HTF_2'  : { type: REC, title: "Hunter's Focus Lv.2", desc: 'HP, Distance +25%', },
    'HTF_3'  : { type: REC, title: "Hunter's Focus Lv.3", desc: 'HP, Distance +30%', },
    'HTF_4'  : { type: REC, title: "Hunter's Focus Lv.4", desc: 'HP, Distance +35%', },
    'HTF_5'  : { type: REC, title: "Hunter's Focus Lv.5", desc: 'HP, Distance +40%', },

    'DSM_1'  : { type: REC, title: "Dash n' Smash Lv.1", desc: 'ATK, Distance +5%', },
    'DSM_2'  : { type: REC, title: "Dash n' Smash Lv.2", desc: 'ATK, Distance +10%', },
    'DSM_3'  : { type: REC, title: "Dash n' Smash Lv.3", desc: 'ATK, Distance +15%', },
    'DSM_4'  : { type: REC, title: "Dash n' Smash Lv.4", desc: 'ATK, Distance +20%', },
    'DSM_5'  : { type: REC, title: "Dash n' Smash Lv.5", desc: 'ATK, Distance +25%', },

    'HRF_1'  : { type: REC, title: "Hero's Focus Lv.1", desc: 'ATK, Distance +20%', },
    'HRF_2'  : { type: REC, title: "Hero's Focus Lv.2", desc: 'ATK, Distance +25%', },
    'HRF_3'  : { type: REC, title: "Hero's Focus Lv.3", desc: 'ATK, Distance +30%', },
    'HRF_4'  : { type: REC, title: "Hero's Focus Lv.4", desc: 'ATK, Distance +35%', },
    'HRF_5'  : { type: REC, title: "Hero's Focus Lv.5", desc: 'ATK, Distance +40%', },
    'HRF_6'  : { type: REC, title: "Hero's Focus Lv.6", desc: 'ATK, Distance +45%', },

    'VSP_1'  : { type: REC, title: 'Vivacious Spark Lv.1', desc: 'Turn comes sooner, HP +10%', },
    'VSP_2'  : { type: REC, title: 'Vivacious Spark Lv.2', desc: 'Turn comes sooner, HP +15%', },
    'VSP_3'  : { type: REC, title: 'Vivacious Spark Lv.3', desc: 'Turn comes much sooner, HP +20%', },
    'VSP_4'  : { type: REC, title: 'Vivacious Spark Lv.4', desc: 'Turn comes massively quicker, HP +25%', },
    'VSP_5'  : { type: REC, title: 'Vivacious Spark Lv.5', desc: 'Turn comes ludicrously quicker, HP +30%', },
    'VSP_6'  : { type: REC, title: 'Vivacious Spark Lv.6', desc: 'Turn comes ludicrously quicker, HP +35%', },

    'BBL_1'  : { type: REC, title: 'Brisk Brawler Lv.1', desc: 'Combo DMG, Distance +5%', },
    'BBL_2'  : { type: REC, title: 'Brisk Brawler Lv.2', desc: 'Combo DMG, Distance +10%', },
    'BBL_3'  : { type: REC, title: 'Brisk Brawler Lv.3', desc: 'Combo DMG, Distance +15%', },
    'BBL_4'  : { type: REC, title: 'Brisk Brawler Lv.4', desc: 'Combo DMG, Distance +20%', },
    'BBL_5'  : { type: REC, title: 'Brisk Brawler Lv.5', desc: 'Combo DMG, Distance +25%', },

    'SSL_1'  : { type: REC, title: "Spry Slaughter Lv.1", desc: 'Combo DMG +30%, Distance +20%', },
    'SSL_2'  : { type: REC, title: "Spry Slaughter Lv.2", desc: 'Combo DMG +35%, Distance +25%', },
    'SSL_3'  : { type: REC, title: "Spry Slaughter Lv.3", desc: 'Combo DMG +45%, Distance +30%', },
    'SSL_4'  : { type: REC, title: "Spry Slaughter Lv.4", desc: 'Combo DMG +55%, Distance +35%', },
    'SSL_5'  : { type: REC, title: "Spry Slaughter Lv.5", desc: 'Combo DMG +65%, Distance +40%', },
    'SSL_6'  : { type: REC, title: "Spry Slaughter Lv.6", desc: 'Combo DMG +75%, Distance +45%', },

    'MGR_1'  : { type: REC, title: "Mage's Rush Lv.1", desc: 'Turn comes sooner, Skill DMG +25%', },
    'MGR_2'  : { type: REC, title: "Mage's Rush Lv.2", desc: 'Turn comes sooner, Skill DMG +35%', },
    'MGR_3'  : { type: REC, title: "Mage's Rush Lv.3", desc: 'Turn comes much sooner, Skill DMG +45%', },
    'MGR_4'  : { type: REC, title: "Mage's Rush Lv.4", desc: 'Turn comes massively quicker, Skill DMG +55%', },
    'MGR_5'  : { type: REC, title: "Mage's Rush Lv.5", desc: 'Turn comes ludicrously quicker, Skill DMG +65%', },
    'MGR_6'  : { type: REC, title: "Mage's Rush Lv.6", desc: 'Turn comes ludicrously quicker, Skill DMG +75%', },

    'ASC_1'  : { type: REC, title: "Agile Sorcery Lv.1", desc: 'Skill DMG +5%, Distance +5%', },
    'ASC_2'  : { type: REC, title: "Agile Sorcery Lv.2", desc: 'Skill DMG +10%, Distance +10%', },
    'ASC_3'  : { type: REC, title: "Agile Sorcery Lv.3", desc: 'Skill DMG +15%, Distance +15%', },
    'ASC_4'  : { type: REC, title: "Agile Sorcery Lv.4", desc: 'Skill DMG +20%, Distance +20%', },
    'ASC_5'  : { type: REC, title: "Agile Sorcery Lv.5", desc: 'Skill DMG +35%, Distance +25%', },

    'WLW_1'  : { type: REC, title: "Warlock's Wings Lv.1", desc: 'Skill DMG +30%, Distance +20%', },
    'WLW_2'  : { type: REC, title: "Warlock's Wings Lv.2", desc: 'Skill DMG +35%, Distance +25%', },
    'WLW_3'  : { type: REC, title: "Warlock's Wings Lv.3", desc: 'Skill DMG +45%, Distance +30%', },
    'WLW_4'  : { type: REC, title: "Warlock's Wings Lv.4", desc: 'Skill DMG +55%, Distance +35%', },
    'WLW_5'  : { type: REC, title: "Warlock's Wings Lv.5", desc: 'Skill DMG +65%, Distance +40%', },
    'WLW_6'  : { type: REC, title: "Warlock's Wings Lv.6", desc: 'Skill DMG +75%, Distance +45%', },

    'TMV_1'  : { type: REC, title: "Terminal Velocity Lv.1", desc: 'Turn comes sooner, Distance +20%', },
    'TMV_2'  : { type: REC, title: "Terminal Velocity Lv.2", desc: 'Turn comes sooner, Distance +25%', },
    'TMV_3'  : { type: REC, title: "Terminal Velocity Lv.3", desc: 'Turn comes much sooner, Distance +30%', },
    'TMV_4'  : { type: REC, title: "Terminal Velocity Lv.4", desc: 'Turn comes massively quicker, Distance +35%', },
    'TMV_5'  : { type: REC, title: "Terminal Velocity Lv.5", desc: 'Turn comes ludicrously quicker, Distance +40%', },
    'TMV_6'  : { type: REC, title: "Terminal Velocity Lv.6", desc: 'Turn comes ludicrously quicker, Distance +45%', },

    'SCT_1'  : { type: STA, title: "Sanctuary Lv.1", desc: 'Party Heal +1%, Party Gauge +2% / turn', },
    'SCT_2'  : { type: STA, title: "Sanctuary Lv.2", desc: 'Party Heal +2%, Party Gauge +3% / turn', },
    'SCT_3'  : { type: STA, title: "Sanctuary Lv.3", desc: 'Party Heal +3%, Party Gauge +5% / turn', },
    'SCT_4'  : { type: STA, title: "Sanctuary Lv.4", desc: 'Party Heal +4%, Party Gauge +7% / turn', },
    'SCT_5'  : { type: STA, title: "Sanctuary Lv.5", desc: 'Party Heal +6%, Party Gauge +10% / turn', },

    'GTT_1'  : { type: REC, title: "Gladiator Tactics Lv.1", desc: 'Turn comes sooner, Combo DMG +25%', },
    'GTT_2'  : { type: REC, title: "Gladiator Tactics Lv.2", desc: 'Turn comes sooner, Combo DMG +35%', },
    'GTT_3'  : { type: REC, title: "Gladiator Tactics Lv.3", desc: 'Turn comes much sooner, Combo DMG +45%', },
    'GTT_4'  : { type: REC, title: "Gladiator Tactics Lv.4", desc: 'Turn comes massively quicker, Combo DMG +55%', },
    'GTT_5'  : { type: REC, title: "Gladiator Tactics Lv.5", desc: 'Turn comes ludicrously quicker, Combo DMG +65%', },
    'GTT_6'  : { type: REC, title: "Gladiator Tactics Lv.6", desc: 'Turn comes ludicrously quicker, Combo DMG +75%', },

    // special type 2
    'SKG_1'  : { type: DAI, title: 'Skill Gauge Speed Up Lv.1', desc: 'Gauge +8% / hit', },
    'SKG_2'  : { type: DAI, title: 'Skill Gauge Speed Up Lv.2', desc: 'Gauge +16% / hit', },
    'SKG_3'  : { type: DAI, title: 'Skill Gauge Speed Up Lv.3', desc: 'Gauge +32% / hit', },
    'SKG_4'  : { type: DAI, title: 'Skill Gauge Speed Up Lv.4', desc: 'Gauge +45% / hit', },
    'SKG_5'  : { type: DAI, title: 'Skill Gauge Speed Up Lv.5', desc: 'Gauge +60% / hit', },
    'SKG_6'  : { type: DAI, title: 'Skill Gauge Ultra Boost Lv.1', desc: 'Gauge +30% / hit', },
    'SKG_7'  : { type: DAI, title: 'Skill Gauge Ultra Boost Lv.2', desc: 'Gauge +45% / hit', },
    'SKG_8'  : { type: DAI, title: 'Skill Gauge Ultra Boost Lv.3', desc: 'Gauge +60% / hit', },
    'SKG_9'  : { type: DAI, title: 'Skill Gauge Ultra Boost Lv.4', desc: 'Gauge +75% / hit', },
    'SKG_10' : { type: DAI, title: 'Skill Gauge Ultra Boost Lv.5', desc: 'Gauge +90% / hit', },

    'SKA_1'  : { type: DAI, title: 'Skill Auto Fill Lv.1', desc: 'Gauge +3% / turn', },
    'SKA_2'  : { type: DAI, title: 'Skill Auto Fill Lv.2', desc: 'Gauge +5% / turn', },
    'SKA_3'  : { type: DAI, title: 'Skill Auto Fill Lv.3', desc: 'Gauge +10% / turn', },
    'SKA_4'  : { type: DAI, title: 'Skill Auto Fill Lv.4', desc: 'Gauge +15% / turn', },
    'SKA_5'  : { type: DAI, title: 'Skill Auto Fill Lv.5', desc: 'Gauge +20% / turn', },
    'SKA_6'  : { type: DAI, title: 'Skill Gauge Auto-Charge Lv.1', desc: 'Gauge +15% / turn', },
    'SKA_7'  : { type: DAI, title: 'Skill Gauge Auto-Charge Lv.2', desc: 'Gauge +20% / turn', },
    'SKA_8'  : { type: DAI, title: 'Skill Gauge Auto-Charge Lv.3', desc: 'Gauge +25% / turn', },
    'SKA_9'  : { type: DAI, title: 'Skill Gauge Auto-Charge Lv.4', desc: 'Gauge +30% / turn', },
    'SKA_10' : { type: DAI, title: 'Skill Gauge Auto-Charge Lv.5', desc: 'Gauge +35% / turn', },

    'COU_1'  : { type: KIT, title: 'Counter Lv.1', desc: '0.5x DMG at close range', },
    'COU_2'  : { type: KIT, title: 'Counter Lv.2', desc: '1x DMG at close range', },
    'COU_3'  : { type: KIT, title: 'Counter Lv.3', desc: '2x DMG at close range', },
    'COU_4'  : { type: KIT, title: 'Counter Lv.4', desc: '5x DMG at close range', },
    'COU_5'  : { type: KIT, title: 'Counter Lv.5', desc: '10x DMG at close range', },

    'FUR_1'  : { type: REC, title: 'Fury Stance Lv.1', desc: 'Boost ATK when HP < 30%', },
    'FUR_2'  : { type: REC, title: 'Fury Stance Lv.2', desc: 'Boost ATK when HP < 30%', },
    'FUR_3'  : { type: REC, title: 'Fury Stance Lv.3', desc: 'Boost ATK when HP < 30%', },
    'FUR_4'  : { type: REC, title: 'Fury Stance Lv.4', desc: 'Boost ATK when HP < 30%', },
    'FUR_5'  : { type: REC, title: 'Fury Stance Lv.5', desc: 'Boost ATK when HP < 30%', },

    'SUR_1'  : { type: DAI, title: 'Survival Stance Lv.1', desc: 'Not die if HP > 70%', },
    'SUR_2'  : { type: DAI, title: 'Survival Stance Lv.2', desc: 'Not die if HP > 50%', },
    'SUR_3'  : { type: DAI, title: 'Survival Stance Lv.3', desc: 'Not die if HP > 28%', },
    'SUR_4'  : { type: DAI, title: 'Survival Stance Lv.4', desc: 'Not die if HP > 20%', },
    'SUR_5'  : { type: DAI, title: 'Survival Stance Lv.5', desc: 'Not die if HP > 12%', },

    'SKR_1'  : { type: DAI, title: "Skill Reserve Lv.1", desc: '10% guage at start', },
    'SKR_2'  : { type: DAI, title: "Skill Reserve Lv.2", desc: '30% guage at start', },
    'SKR_3'  : { type: DAI, title: "Skill Reserve Lv.3", desc: '50% guage at start', },
    'SKR_4'  : { type: DAI, title: "Skill Reserve Lv.4", desc: '70% guage at start', },
    'SKR_5'  : { type: DAI, title: "Skill Reserve Lv.5", desc: '100% guage at start', },

    // attack attribute
    'FIR_1'  : { type: STA, title: 'Fire Attack Lv.1', desc: '+300 Fire DMG', },
    'FIR_2'  : { type: STA, title: 'Fire Attack Lv.2', desc: '+550 Fire DMG', },
    'FIR_3'  : { type: STA, title: 'Fire Attack Lv.3', desc: '+950 Fire DMG', },
    'FIR_4'  : { type: STA, title: 'Fire Attack Lv.4', desc: '+1400 Fire DMG', },
    'FIR_5'  : { type: STA, title: 'Fire Attack Lv.5', desc: '+2150 Fire DMG', },
    'FIR_6'  : { type: STA, title: 'Burning Attack Lv.1', desc: '+1400 Fire DMG', },
    'FIR_7'  : { type: STA, title: 'Burning Attack Lv.2', desc: '+2150 Fire DMG', },
    'FIR_8'  : { type: STA, title: 'Burning Attack Lv.3', desc: '+2950 Fire DMG', },
    'FIR_9'  : { type: STA, title: 'Burning Attack Lv.4', desc: '+3800 Fire DMG', },
    'FIR_10' : { type: STA, title: 'Burning Attack Lv.5', desc: '+4700 Fire DMG', },

    'ICE_1'  : { type: STA, title: 'Ice Attack Lv.1', desc: '+300 Ice DMG', },
    'ICE_2'  : { type: STA, title: 'Ice Attack Lv.2', desc: '+550 Ice DMG', },
    'ICE_3'  : { type: STA, title: 'Ice Attack Lv.3', desc: '+950 Ice DMG', },
    'ICE_4'  : { type: STA, title: 'Ice Attack Lv.4', desc: '+1400 Ice DMG', },
    'ICE_5'  : { type: STA, title: 'Ice Attack Lv.5', desc: '+2150 Ice DMG', },
    'ICE_6'  : { type: STA, title: 'Arctic Attack Lv.1', desc: '+1400 Ice DMG', },
    'ICE_7'  : { type: STA, title: 'Arctic Attack Lv.2', desc: '+2150 Ice DMG', },
    'ICE_8'  : { type: STA, title: 'Arctic Attack Lv.3', desc: '+2950 Ice DMG', },
    'ICE_9'  : { type: STA, title: 'Arctic Attack Lv.4', desc: '+3800 Ice DMG', },
    'ICE_10' : { type: STA, title: 'Arctic Attack Lv.5', desc: '+4700 Ice DMG', },
    'ICE_11' : { type: STA, title: 'Arctic Attack Lv.6', desc: '+5600 Ice DMG', },

    'ELE_1'  : { type: STA, title: 'Elec Attack Lv.1', desc: '+300 Elec DMG', },
    'ELE_2'  : { type: STA, title: 'Elec Attack Lv.2', desc: '+550 Elec DMG', },
    'ELE_3'  : { type: STA, title: 'Elec Attack Lv.3', desc: '+950 Elec DMG', },
    'ELE_4'  : { type: STA, title: 'Elec Attack Lv.4', desc: '+1400 Elec DMG', },
    'ELE_5'  : { type: STA, title: 'Elec Attack Lv.5', desc: '+2150 Elec DMG', },
    'ELE_6'  : { type: STA, title: 'Shock Attack Lv.1', desc: '+1400 Elec DMG', },
    'ELE_7'  : { type: STA, title: 'Shock Attack Lv.2', desc: '+2150 Elec DMG', },
    'ELE_8'  : { type: STA, title: 'Shock Attack Lv.3', desc: '+2950 Elec DMG', },
    'ELE_9'  : { type: STA, title: 'Shock Attack Lv.4', desc: '+3800 Elec DMG', },
    'ELE_10' : { type: STA, title: 'Shock Attack Lv.5', desc: '+4700 Elec DMG', },
    'ELE_11' : { type: STA, title: 'Shock Attack Lv.6', desc: '+5600 Elec DMG', },

    'WND_1'  : { type: STA, title: 'Wind Attack Lv.1', desc: '+300 Wind DMG', },
    'WND_2'  : { type: STA, title: 'Wind Attack Lv.2', desc: '+550 Wind DMG', },
    'WND_3'  : { type: STA, title: 'Wind Attack Lv.3', desc: '+950 Wind DMG', },
    'WND_4'  : { type: STA, title: 'Wind Attack Lv.4', desc: '+1400 Wind DMG', },
    'WND_5'  : { type: STA, title: 'Wind Attack Lv.5', desc: '+2150 Wind DMG', },
    'WND_6'  : { type: STA, title: 'Cyclone Attack Lv.1', desc: '+1400 Wind DMG', },
    'WND_7'  : { type: STA, title: 'Cyclone Attack Lv.2', desc: '+2150 Wind DMG', },
    'WND_8'  : { type: STA, title: 'Cyclone Attack Lv.3', desc: '+2950 Wind DMG', },
    'WND_9'  : { type: STA, title: 'Cyclone Attack Lv.4', desc: '+3800 Wind DMG', },
    'WND_10' : { type: STA, title: 'Cyclone Attack Lv.5', desc: '+4700 Wind DMG', },

    'LHT_1'  : { type: STA, title: 'Light Attack Lv.1', desc: '+300 Light DMG', },
    'LHT_2'  : { type: STA, title: 'Light Attack Lv.2', desc: '+550 Light DMG', },
    'LHT_3'  : { type: STA, title: 'Light Attack Lv.3', desc: '+950 Light DMG', },
    'LHT_4'  : { type: STA, title: 'Light Attack Lv.4', desc: '+1400 Light DMG', },
    'LHT_5'  : { type: STA, title: 'Light Attack Lv.5', desc: '+2150 Light DMG', },
    'LHT_6'  : { type: STA, title: 'Luminous Attack Lv.1', desc: '+1400 Light DMG', },
    'LHT_7'  : { type: STA, title: 'Luminous Attack Lv.2', desc: '+2150 Light DMG', },
    'LHT_8'  : { type: STA, title: 'Luminous Attack Lv.3', desc: '+2950 Light DMG', },
    'LHT_9'  : { type: STA, title: 'Luminous Attack Lv.4', desc: '+3800 Light DMG', },
    'LHT_10' : { type: STA, title: 'Luminous Attack Lv.5', desc: '+4700 Light DMG', },

    'DRK_1'  : { type: STA, title: 'Dark Attack Lv.1', desc: '+300 Dark DMG', },
    'DRK_2'  : { type: STA, title: 'Dark Attack Lv.2', desc: '+550 Dark DMG', },
    'DRK_3'  : { type: STA, title: 'Dark Attack Lv.3', desc: '+950 Dark DMG', },
    'DRK_4'  : { type: STA, title: 'Dark Attack Lv.4', desc: '+1400 Dark DMG', },
    'DRK_5'  : { type: STA, title: 'Dark Attack Lv.5', desc: '+2150 Dark DMG', },
    'DRK_6'  : { type: STA, title: 'Shadow Attack Lv.1', desc: '+1400 Dark DMG', },
    'DRK_7'  : { type: STA, title: 'Shadow Attack Lv.2', desc: '+2150 Dark DMG', },
    'DRK_8'  : { type: STA, title: 'Shadow Attack Lv.3', desc: '+2950 Dark DMG', },
    'DRK_9'  : { type: STA, title: 'Shadow Attack Lv.4', desc: '+3800 Dark DMG', },
    'DRK_10' : { type: STA, title: 'Shadow Attack Lv.5', desc: '+4700 Dark DMG', },
   
    // defence attribute
    'FIRD_1'  : { type: KIT, title: 'Defense Fire Lv.1', desc: '-15% Fire DMG', },
    'FIRD_2'  : { type: KIT, title: 'Defense Fire Lv.2', desc: '-20% Fire DMG', },
    'FIRD_3'  : { type: KIT, title: 'Defense Fire Lv.3', desc: '-25% Fire DMG', },
    'FIRD_4'  : { type: KIT, title: 'Defense Fire Lv.4', desc: '-35% Fire DMG', },
    'FIRD_5'  : { type: KIT, title: 'Defense Fire Lv.5', desc: '-45% Fire DMG', },
    'FIRD_10' : { type: KIT, title: 'Howl of Flame Guard', desc: '-55% Fire DMG', },

    'ICED_1'  : { type: KIT, title: 'Defense Ice Lv.1', desc: '-15% Ice DMG', },
    'ICED_2'  : { type: KIT, title: 'Defense Ice Lv.2', desc: '-20% Ice DMG', },
    'ICED_3'  : { type: KIT, title: 'Defense Ice Lv.3', desc: '-25% Ice DMG', },
    'ICED_4'  : { type: KIT, title: 'Defense Ice Lv.4', desc: '-35% Ice DMG', },
    'ICED_5'  : { type: KIT, title: 'Defense Ice Lv.5', desc: '-45% Ice DMG', },

    'ELED_1'  : { type: KIT, title: 'Defense Elec Lv.1', desc: '-15% Elec DMG', },
    'ELED_2'  : { type: KIT, title: 'Defense Elec Lv.2', desc: '-20% Elec DMG', },
    'ELED_3'  : { type: KIT, title: 'Defense Elec Lv.3', desc: '-25% Elec DMG', },
    'ELED_4'  : { type: KIT, title: 'Defense Elec Lv.4', desc: '-35% Elec DMG', },
    'ELED_5'  : { type: KIT, title: 'Defense Elec Lv.5', desc: '-45% Elec DMG', },

    'WNDD_1'  : { type: KIT, title: 'Defense Wind Lv.1', desc: '-15% Wind DMG', },
    'WNDD_2'  : { type: KIT, title: 'Defense Wind Lv.2', desc: '-20% Wind DMG', },
    'WNDD_3'  : { type: KIT, title: 'Defense Wind Lv.3', desc: '-25% Wind DMG', },
    'WNDD_4'  : { type: KIT, title: 'Defense Wind Lv.4', desc: '-35% Wind DMG', },
    'WNDD_5'  : { type: KIT, title: 'Defense Wind Lv.5', desc: '-45% Wind DMG', },

    'LHTD_1'  : { type: KIT, title: 'Defense Light Lv.1', desc: '-15% Light DMG', },
    'LHTD_2'  : { type: KIT, title: 'Defense Light Lv.2', desc: '-20% Light DMG', },
    'LHTD_3'  : { type: KIT, title: 'Defense Light Lv.3', desc: '-25% Light DMG', },
    'LHTD_4'  : { type: KIT, title: 'Defense Light Lv.4', desc: '-35% Light DMG', },
    'LHTD_5'  : { type: KIT, title: 'Defense Light Lv.5', desc: '-45% Light DMG', },

    'DRKD_1'  : { type: KIT, title: 'Defense Dark Lv.1', desc: '-15% Dark DMG', },
    'DRKD_2'  : { type: KIT, title: 'Defense Dark Lv.2', desc: '-20% Dark DMG', },
    'DRKD_3'  : { type: KIT, title: 'Defense Dark Lv.3', desc: '-25% Dark DMG', },
    'DRKD_4'  : { type: KIT, title: 'Defense Dark Lv.4', desc: '-35% Dark DMG', },
    'DRKD_5'  : { type: KIT, title: 'Defense Dark Lv.5', desc: '-45% Dark DMG', },

    // party support
    'RTB_1'  : { type: PAR, title: 'Rage of the Beast Lv.1', desc: 'Horn weapon ATK +3%', },
    'RTB_2'  : { type: PAR, title: 'Rage of the Beast Lv.2', desc: 'Horn weapon ATK +5%', },
    'RTB_3'  : { type: PAR, title: 'Rage of the Beast Lv.3', desc: 'Horn weapon ATK +7%', },
    'RTB_4'  : { type: PAR, title: 'Rage of the Beast Lv.4', desc: 'Horn weapon ATK +10%', },
    'RTB_5'  : { type: PAR, title: 'Rage of the Beast Lv.5', desc: 'Horn weapon ATK +15%', },

    'MCR_1'  : { type: PAR, title: 'Mystic Crystalization Lv.1', desc: 'Ore armor DEF +3%', },
    'MCR_2'  : { type: PAR, title: 'Mystic Crystalization Lv.2', desc: 'Ore armor DEF +5%', },
    'MCR_3'  : { type: PAR, title: 'Mystic Crystalization Lv.3', desc: 'Ore armor DEF +7%', },
    'MCR_4'  : { type: PAR, title: 'Mystic Crystalization Lv.4', desc: 'Ore armor DEF +10%', },
    'MCR_5'  : { type: PAR, title: 'Mystic Crystalization Lv.5', desc: 'Ore armor DEF +15%', },

    'SBI_1'  : { type: PAR, title: 'Soul of Blood and Iron Lv.1', desc: 'Metal helmet HP +3%', },
    'SBI_2'  : { type: PAR, title: 'Soul of Blood and Iron Lv.2', desc: 'Metal helmet HP +5%', },
    'SBI_3'  : { type: PAR, title: 'Soul of Blood and Iron Lv.3', desc: 'Metal helmet HP +7%', },
    'SBI_4'  : { type: PAR, title: 'Soul of Blood and Iron Lv.4', desc: 'Metal helmet HP +10%', },
    'SBI_5'  : { type: PAR, title: 'Soul of Blood and Iron Lv.5', desc: 'Metal helmet HP +15%', },

    'BAT_1'  : { type: PAR, title: 'Blessing of the Ancient Tree Lv.1', desc: 'Party HP +1%', },
    'BAT_2'  : { type: PAR, title: 'Blessing of the Ancient Tree Lv.2', desc: 'Party HP +2%', },
    'BAT_3'  : { type: PAR, title: 'Blessing of the Ancient Tree Lv.3', desc: 'Party HP +3%', },
    'BAT_4'  : { type: PAR, title: 'Blessing of the Ancient Tree Lv.4', desc: 'Party HP +5%', },
    'BAT_5'  : { type: PAR, title: 'Blessing of the Ancient Tree Lv.5', desc: 'Party HP +7%', },

    'DOA_1'  : { type: PAR, title: 'Divine Ore Aegis Lv.1', desc: 'Ore helmet HP +3%', },
    'DOA_2'  : { type: PAR, title: 'Divine Ore Aegis Lv.2', desc: 'Ore helmet HP +5%', },
    'DOA_3'  : { type: PAR, title: 'Divine Ore Aegis Lv.3', desc: 'Ore helmet HP +7%', },
    'DOA_4'  : { type: PAR, title: 'Divine Ore Aegis Lv.4', desc: 'Ore helmet HP +10%', },
    'DOA_5'  : { type: PAR, title: 'Divine Ore Aegis Lv.5', desc: 'Ore helmet HP +15%', },

    'BIA_1'  : { type: PAR, title: 'Black Iron Ambition Lv.1', desc: 'Metal weapon ATK +3%', },
    'BIA_2'  : { type: PAR, title: 'Black Iron Ambition Lv.2', desc: 'Metal weapon ATK +5%', },
    'BIA_3'  : { type: PAR, title: 'Black Iron Ambition Lv.3', desc: 'Metal weapon ATK +7%', },
    'BIA_4'  : { type: PAR, title: 'Black Iron Ambition Lv.4', desc: 'Metal weapon ATK +10%', },
    'BIA_5'  : { type: PAR, title: 'Black Iron Ambition Lv.5', desc: 'Metal weapon ATK +15%', },

    'ABS_1'  : { type: PAR, title: 'Absolute Shield Lv.1', desc: 'Metal armor DEF +3%', },
    'ABS_2'  : { type: PAR, title: 'Absolute Shield Lv.2', desc: 'Metal armor DEF +5%', },
    'ABS_3'  : { type: PAR, title: 'Absolute Shield Lv.3', desc: 'Metal armor DEF +7%', },
    'ABS_4'  : { type: PAR, title: 'Absolute Shield Lv.4', desc: 'Metal armor DEF +10%', },
    'ABS_5'  : { type: PAR, title: 'Absolute Shield Lv.5', desc: 'Metal armor DEF +15%', },

    'SBK_1'  : { type: PAR, title: 'Spirit of the Beast King Lv.1', desc: 'Horn helmet HP +3%', },
    'SBK_2'  : { type: PAR, title: 'Spirit of the Beast King Lv.2', desc: 'Horn helmet HP +5%', },
    'SBK_3'  : { type: PAR, title: 'Spirit of the Beast King Lv.3', desc: 'Horn helmet HP +7%', },
    'SBK_4'  : { type: PAR, title: 'Spirit of the Beast King Lv.4', desc: 'Horn helmet HP +10%', },
    'SBK_5'  : { type: PAR, title: 'Spirit of the Beast King Lv.5', desc: 'Horn helmet HP +15%', },

    'DVR_1'  : { type: PAR, title: 'Divine Revelation Lv.1', desc: 'Party ATK +1%', },
    'DVR_2'  : { type: PAR, title: 'Divine Revelation Lv.2', desc: 'Party ATK +2%', },
    'DVR_3'  : { type: PAR, title: 'Divine Revelation Lv.3', desc: 'Party ATK +3%', },
    'DVR_4'  : { type: PAR, title: 'Divine Revelation Lv.4', desc: 'Party ATK +5%', },
    'DVR_5'  : { type: PAR, title: 'Divine Revelation Lv.5', desc: 'Party ATK +7%', },

    'DFS_1'  : { type: PAR, title: 'Demon Fang Shield Lv.1', desc: 'Horn armor DEF +3%', },
    'DFS_2'  : { type: PAR, title: 'Demon Fang Shield Lv.2', desc: 'Horn armor DEF +5%', },
    'DFS_3'  : { type: PAR, title: 'Demon Fang Shield Lv.3', desc: 'Horn armor DEF +7%', },
    'DFS_4'  : { type: PAR, title: 'Demon Fang Shield Lv.4', desc: 'Horn armor DEF +10%', },
    'DFS_5'  : { type: PAR, title: 'Demon Fang Shield Lv.5', desc: 'Horn armor DEF +15%', },

    'SWA_1'  : { type: PAR, title: 'Shockwave Alloy Lv.1', desc: 'Ore weapon ATK +3%', },
    'SWA_2'  : { type: PAR, title: 'Shockwave Alloy Lv.2', desc: 'Ore weapon ATK +5%', },
    'SWA_3'  : { type: PAR, title: 'Shockwave Alloy Lv.3', desc: 'Ore weapon ATK +7%', },
    'SWA_4'  : { type: PAR, title: 'Shockwave Alloy Lv.4', desc: 'Ore weapon ATK +10%', },
    'SWA_5'  : { type: PAR, title: 'Shockwave Alloy Lv.5', desc: 'Ore weapon ATK +15%', },

    'KTS_1'  : { type: PAR, title: "Spirit King's Tree Shield Lv.1", desc: 'Party DEF +3%', },
    'KTS_2'  : { type: PAR, title: "Spirit King's Tree Shield Lv.2", desc: 'Party DEF +5%', },
    'KTS_3'  : { type: PAR, title: "Spirit King's Tree Shield Lv.3", desc: 'Party DEF +7%', },
    'KTS_4'  : { type: PAR, title: "Spirit King's Tree Shield Lv.4", desc: 'Party DEF +10%', },
    'KTS_5'  : { type: PAR, title: "Spirit King's Tree Shield Lv.5", desc: 'Party DEF +15%', },

    'GOO_1'  : { type: PAR, title: "Gait of Old Lv.1", desc: 'Party Distance +5%', },
    'GOO_2'  : { type: PAR, title: "Gait of Old Lv.2", desc: 'Party Distance +10%', },
    'GOO_3'  : { type: PAR, title: "Gait of Old Lv.3", desc: 'Party Distance +15%', },
    'GOO_4'  : { type: PAR, title: "Gait of Old Lv.4", desc: 'Party Distance +20%', },
    'GOO_5'  : { type: PAR, title: "Gait of Old Lv.5", desc: 'Party Distance +25%', },

    'LSG_1'  : { type: PAR, title: "Love of the Sun God Lv.1", desc: 'Party Heal +1%', },
    'LSG_2'  : { type: PAR, title: "Love of the Sun God Lv.2", desc: 'Party Heal +2%', },
    'LSG_3'  : { type: PAR, title: "Love of the Sun God Lv.3", desc: 'Party Heal +3%', },
    'LSG_4'  : { type: PAR, title: "Love of the Sun God Lv.4", desc: 'Party Heal +5%', },
    'LSG_5'  : { type: PAR, title: "Love of the Sun God Lv.5", desc: 'Party Heal +7%', },
    'LSG_6'  : { type: PAR, title: "Love of the Sun God Lv.6", desc: 'Party Heal +10%', },

    'HDB_1'  : { type: PAR, title: 'Hardened Briars Lv.1', desc: 'Wood weapon ATK +3%', },
    'HDB_2'  : { type: PAR, title: 'Hardened Briars Lv.2', desc: 'Wood weapon ATK +5%', },
    'HDB_3'  : { type: PAR, title: 'Hardened Briars Lv.3', desc: 'Wood weapon ATK +7%', },
    'HDB_4'  : { type: PAR, title: 'Hardened Briars Lv.4', desc: 'Wood weapon ATK +10%', },
    'HDB_5'  : { type: PAR, title: 'Hardened Briars Lv.5', desc: 'Wood weapon ATK +15%', },

    'AVG_1'  : { type: PAR, title: "Ares's Vigor Lv.1", desc: 'Party Combo DMG +3%', },
    'AVG_2'  : { type: PAR, title: "Ares's Vigor Lv.2", desc: 'Party Combo DMG +5%', },
    'AVG_3'  : { type: PAR, title: "Ares's Vigor Lv.3", desc: 'Party Combo DMG +10%', },
    'AVG_4'  : { type: PAR, title: "Ares's Vigor Lv.4", desc: 'Party Combo DMG +15%', },
    'AVG_5'  : { type: PAR, title: "Ares's Vigor Lv.5", desc: 'Party Combo DMG +25%', },
    'AVG_6'  : { type: PAR, title: "Ares's Vigor Lv.6", desc: 'Party Combo DMG +30%', },

    'TOP_1'  : { type: PAR, title: "Tears of Phoebe Lv.1", desc: 'Party Gauge +3% / turn', },
    'TOP_2'  : { type: PAR, title: "Tears of Phoebe Lv.2", desc: 'Party Gauge +5% / turn', },
    'TOP_3'  : { type: PAR, title: "Tears of Phoebe Lv.3", desc: 'Party Gauge +7% / turn', },
    'TOP_4'  : { type: PAR, title: "Tears of Phoebe Lv.4", desc: 'Party Gauge +9% / turn', },
    'TOP_5'  : { type: PAR, title: "Tears of Phoebe Lv.5", desc: 'Party Gauge +11% / turn', },

    'WSM_1'  : { type: PAR, title: "Wisdom of the Shaman Lv.1", desc: 'Party Skill DMG +3%', },
    'WSM_2'  : { type: PAR, title: "Wisdom of the Shaman Lv.2", desc: 'Party Skill DMG +5%', },
    'WSM_3'  : { type: PAR, title: "Wisdom of the Shaman Lv.3", desc: 'Party Skill DMG +10%', },
    'WSM_4'  : { type: PAR, title: "Wisdom of the Shaman Lv.4", desc: 'Party Skill DMG +15%', },
    'WSM_5'  : { type: PAR, title: "Wisdom of the Shaman Lv.5", desc: 'Party Skill DMG +25%', },
    'WSM_6'  : { type: PAR, title: "Wisdom of the Shaman Lv.6", desc: 'Party Skill DMG +30%', },

    'JWF_1'  : { type: PAR, title: 'Jewel of Fertility Lv.1', desc: 'Ore helmet HP +3%, Ore weapon ATK +3%', },
    'JWF_2'  : { type: PAR, title: 'Jewel of Fertility Lv.2', desc: 'Ore helmet HP +5%, Ore weapon ATK +5%', },
    'JWF_3'  : { type: PAR, title: 'Jewel of Fertility Lv.3', desc: 'Ore helmet HP +7%, Ore weapon ATK +7%', },
    'JWF_4'  : { type: PAR, title: 'Jewel of Fertility Lv.4', desc: 'Ore helmet HP +10%, Ore weapon ATK +10%', },
    'JWF_5'  : { type: PAR, title: 'Jewel of Fertility Lv.5', desc: 'Ore helmet HP +15%, Ore weapon ATK +15%', },

    'STB_1'  : { type: PAR, title: 'Steel Blessing Lv.1', desc: 'Metal helmet HP +3%, Metal weapon ATK +3%', },
    'STB_2'  : { type: PAR, title: 'Steel Blessing Lv.2', desc: 'Metal helmet HP +5%, Metal weapon ATK +5%', },
    'STB_3'  : { type: PAR, title: 'Steel Blessing Lv.3', desc: 'Metal helmet HP +7%, Metal weapon ATK +7%', },
    'STB_4'  : { type: PAR, title: 'Steel Blessing Lv.4', desc: 'Metal helmet HP +10%, Metal weapon ATK +10%', },
    'STB_5'  : { type: PAR, title: 'Steel Blessing Lv.5', desc: 'Metal helmet HP +15%, Metal weapon ATK +15%', },
    'STB_6'  : { type: PAR, title: 'Steel Blessing Lv.6', desc: 'Metal helmet HP +20%, Metal weapon ATK +20%', },

    'SMR_1'  : { type: PAR, title: "Waltz of the Samurai Lv.1", desc: 'Party ATK DMG +1%, Party Distance +5%', },
    'SMR_2'  : { type: PAR, title: "Waltz of the Samurai Lv.2", desc: 'Party ATK DMG +2%, Party Distance +10%', },
    'SMR_3'  : { type: PAR, title: "Waltz of the Samurai Lv.3", desc: 'Party ATK DMG +3%, Party Distance +15%', },
    'SMR_4'  : { type: PAR, title: "Waltz of the Samurai Lv.4", desc: 'Party ATK DMG +5%, Party Distance +20%', },
    'SMR_5'  : { type: PAR, title: "Waltz of the Samurai Lv.5", desc: 'Party ATK DMG +7%, Party Distance +25%', },
    'SMR_6'  : { type: PAR, title: "Waltz of the Samurai Lv.6", desc: 'Party ATK DMG +10%, Party Distance +30%', },

    'HKM_1'  : { type: PAR, title: 'Howl of Kamui Lv.1', desc: 'Horn helmet HP +3%, Horn weapon ATK +3%', },
    'HKM_2'  : { type: PAR, title: 'Howl of Kamui Lv.2', desc: 'Horn helmet HP +5%, Horn weapon ATK +5%', },
    'HKM_3'  : { type: PAR, title: 'Howl of Kamui Lv.3', desc: 'Horn helmet HP +7%, Horn weapon ATK +7%', },
    'HKM_4'  : { type: PAR, title: 'Howl of Kamui Lv.4', desc: 'Horn helmet HP +10%, Horn weapon ATK +10%', },
    'HKM_5'  : { type: PAR, title: 'Howl of Kamui Lv.5', desc: 'Horn helmet HP +15%, Horn weapon ATK +15%', },

    'IVT_1'  : { type: PAR, title: "Invictus Lv.1", desc: 'Party Combo DMG +3%, Party ATK +1%', },
    'IVT_2'  : { type: PAR, title: "Invictus Lv.2", desc: 'Party Combo DMG +5%, Party ATK +2%', },
    'IVT_3'  : { type: PAR, title: "Invictus Lv.3", desc: 'Party Combo DMG +10%, Party ATK +3%', },
    'IVT_4'  : { type: PAR, title: "Invictus Lv.4", desc: 'Party Combo DMG +15%, Party ATK +5%', },
    'IVT_5'  : { type: PAR, title: "Invictus Lv.5", desc: 'Party Combo DMG +25%, Party ATK +7%', },
    'IVT_6'  : { type: PAR, title: "Invictus Lv.6", desc: 'Party Combo DMG +35%, Party ATK +10%', },

    'DVS_1'  : { type: PAR, title: "Divine Sorcery Lv.1", desc: 'Party Skill DMG +3%, Party ATK +1%', },
    'DVS_2'  : { type: PAR, title: "Divine Sorcery Lv.2", desc: 'Party Skill DMG +5%, Party ATK +2%', },
    'DVS_3'  : { type: PAR, title: "Divine Sorcery Lv.3", desc: 'Party Skill DMG +10%, Party ATK +3%', },
    'DVS_4'  : { type: PAR, title: "Divine Sorcery Lv.4", desc: 'Party Skill DMG +15%, Party ATK +5%', },
    'DVS_5'  : { type: PAR, title: "Divine Sorcery Lv.5", desc: 'Party Skill DMG +25%, Party ATK +7%', },
    'DVS_6'  : { type: PAR, title: "Divine Sorcery Lv.6", desc: 'Party Skill DMG +30%, Party ATK +10%', },

    'WRC_1'  : { type: PAR, title: "Warrior's Creed Lv.1", desc: 'Party Distance DMG +5%, Party ATK +1%', },
    'WRC_2'  : { type: PAR, title: "Warrior's Creed Lv.2", desc: 'Party Distance DMG +10%, Party ATK +2%', },
    'WRC_3'  : { type: PAR, title: "Warrior's Creed Lv.3", desc: 'Party Distance DMG +15%, Party ATK +3%', },
    'WRC_4'  : { type: PAR, title: "Warrior's Creed Lv.4", desc: 'Party Distance DMG +20%, Party ATK +5%', },
    'WRC_5'  : { type: PAR, title: "Warrior's Creed Lv.5", desc: 'Party Distance DMG +25%, Party ATK +7%', },
    'WRC_6'  : { type: PAR, title: "Warrior's Creed Lv.6", desc: 'Party Distance DMG +30%, Party ATK +10%', },
}
