var WEAPONS = [
    {
        code: 'BLZ_DNS',    name: "Ultra Blaze of Darkness",
        type: WPN_LANCE,    material: IRON,
        score: 2812,        slots: 'DRK_10-FIR_5-CMB_10-CIR-DAI|CIR',
        skill: 'GVT_FLD_3', evt: true,
        cost: 37,
    },
    {
        rcode: 3018,    name: "Blaze of Darkness",
        type: WPN_LANCE,    material: IRON,
        score: 2681,        slots: 'DRK_5-FIR_4-CMB_5-CIR-DAI|CIR',
        skill: 'GVT_FLD_2', evt: true,
        cost: 34,
    },
    {
        code: 'SCT_NGR',    name: "Divine Scepter of Naga Raja",
        type: WPN_STAFF,    material: HORN,
        score: 2464,        slots: 'SKA_3-HEA_3-STA-TRI-CIR|CIR',
        skill: 'GAL_ARW_2', cost: 34,
    },
    {
        code: 'LNC_VLC',    name: "Lance of Valcanalia",
        type: WPN_LANCE,    material: IRON,
        score: 3068,        slots: 'FIR_10-CMB_9-CIR-DAI-CIR|TRI',
        skill: 'IFN_RAY_2', limited: true,
        cost: 40,
    },
    {
        code: 'DGN_IIF',    name: "Ultra Dragon Ice Inferno",
        type: WPN_SWORD,    material: HORN,
        score: 2760,        slots: 'SKG_9-ICE_10-FIR_5-CIR-TRI|CIR',
        skill: 'ICE_EDG_3', evt: true,
        cost: 37,
    },
    {
        rcode: 2005,    name: "Dragon Ice Inferno",
        type: WPN_SWORD,    material: HORN,
        score: 2545,        slots: 'SKG_3-ICE_4-FIR_3-CIR-TRI|CIR',
        skill: 'ICE_EDG_1', evt: true,
        cost: 41,
    },
    {
        code: 'REG_INL',    name: "Reginleiv",
        type: WPN_SWORD,    material: HORN,
        score: 2942,        slots: 'CMB_5-LHT_3-LHT_3-TRI-TRI|CIR',
        skill: 'SPD_BMR_2', cost: 34,
    },
    {
        code: 'VEX_IFT',    name: "Vexed Rod of Ifrit",
        type: WPN_STAFF,    material: CRYS,
        score: 2414,        slots: 'FIR_5-SKA_3-TRI-CIR-TRI|KIT',
        skill: 'FLM_BLD_2', cost: 34,
    },
    {
        code: 'GOD_HND',    name: "Godhand",
        type: WPN_FIST,     material: IRON,
        score: 1552,        slots: 'LHT_5-HAS_3-TRI-CIR-CIR|CIR',
        skill: 'SPD_BMR_2', cost: 34,
    },
    {
        code: 'FUT_MTM',    name: "Futsu-no-Mitama",
        type: WPN_SWORD,    material: WOOD,
        score: 2932,        slots: 'LHT_5-SKL_5-HAS_4-CIR-KIT|TRI',
        skill: 'DVN_SBR_2', cost: 34,
    },
    {
        code: 'UBR_BWK',    name: "Uber Bergwerk",
        type: WPN_HMMR,     material: CRYS,
        score: 2730,        slots: 'DRK_5-CMB_4-CIR-TRI-KIT|TRI',
        skill: 'GVT_FLD_2', cost: 35,
    },
    {
        code: 'FST_HMD',    name: "Fist of Heimdall",
        type: WPN_FIST,     material: CRYS,
        score: 1834,        slots: 'LHT_10-HAS_9-TRI-CIR-TRI|DAI',
        skill: 'LHT_CRS_3', limited: true,
        cost: 40,
    },
    {
        code: 'FLR_CYC',    name: "Ultra Flare Cyclone",
        type: WPN_HMMR,     material: HORN,
        score: 2810,        slots: 'CMB_10-FIR_10-WND_5-DAI-TRI|CIR',
        skill: 'RAG_AGN_3', evt: true,
        cost: 37,
    },
    {
        rcode: 1112,    name: "Flare Cyclone",
        type: WPN_HMMR,     material: HORN,
        score: 2600,        slots: 'CMB_5-FIR_5-WND_4-DAI-TRI|CIR',
        skill: 'LVA_FLM_2', evt: true,
        cost: 34,
    },
    {
        code: 'DVN_DSP',    name: "Divine Desperation",
        type: WPN_FIST,     material: IRON,
        score: 1582,        slots: 'DRK_4-HAS_3-TRI-CIR-TRI|CIR',
        skill: 'DVL_CLW_2', cost: 34,
    },
    {
        code: 'THE_ABY',    name: "The Abyss",
        type: WPN_SWORD,    material: HORN,
        score: 2927,        slots: 'DRK_5-SKL_4-REC-TRI-DAI|TRI',
        skill: 'LVA_FLM_2', cost: 34,
    },
    {
        code: 'TOT_SPR',    name: "Trick-or-Treat Spear",
        type: WPN_LANCE,    material: WOOD,
        score: 2877,        slots: 'DRK_5-HEA_4-SKA_3-TRI-CIR|REC',
        skill: 'RAS_BMR_3', limited: true,
        cost: 35,
    },
    {
        code: 'JCK_STF',    name: "Jack O' Lantern Staff",
        type: WPN_STAFF,    material: WOOD,
        score: 2584,        slots: 'CMB_4-CMB_4-SKA_3-STA-TRI|TRI',
        skill: 'LHT_CRS_2', limited: true,
        cost: 35,
    },
    {
        code: 'ZAH_STF',    name: "Zahhak Staff",
        type: WPN_STAFF,    material: HORN,
        score: 2527,        slots: 'SKA_4-SKL_4-SKL_4-CIR-TRI|CIR',
        skill: 'SPD_BMR_2', cost: 35,
    },
    {
        code: 'CAL_BLG',    name: "Caladbolg",
        type: WPN_SWORD,    material: HORN,
        score: 2912,        slots: 'HAS_5-SKL_4-CIR-DAI-KIT|REC',
        skill: 'MTR_STM_2', cost: 34,
    },
    {
        code: 'ICR_GLC',    name: "Ice Rod of Glacies",
        type: WPN_STAFF,    material: CRYS,
        score: 2451,        slots: 'ICE_5-SKA_3-KIT-CIR-CIR|TRI',
        skill: 'ICE_EDG_2', cost: 34,
    },
    {
        code: 'FST_YGG',    name: "Fist of Yggdrasil",
        type: WPN_FIST,     material: WOOD,
        score: 1407,        slots: 'SKL_5-HAS_3-DAI-CIR-TRI|KIT',
        skill: 'DRN_BST_2', evt: true,
        cost: 34,
    },
    {
        code: 'MIS_ANM',    name: "Misteltein Anima",
        type: WPN_LANCE,    material: WOOD,
        score: 2746,        slots: 'SKL_3-SKA_3-TRI-TRI-CIR|CIR',
        skill: 'DRN_BST_2', cost: 34,
    },
    {
        code: 'HNR_FRN',    name: "Holy Night Rod of Fafner",
        type: WPN_STAFF,    material: HORN,
        score: 2741,        slots: 'FIR_10-SKA_4-CIR-TRI-STA|CIR',
        skill: 'FLM_BLD_3', limited: true,
        cost: 40,
    },
    {
        code: 'HLY_OBL',    name: "Holy Obelisk",
        type: WPN_LANCE,    material: FRAG,
        score: 2723,        slots: 'DAI-CIR-CIR-TRI-REC|TRI',
        skill: 'GVT_FLD_2', evt: true,
        cost: 34,
    },
    {
        code: 'HLY_TTM',    name: "Holy Testament",
        type: WPN_HMMR,     material: HORN,
        score: 2743,        slots: 'SKL_5-HEA_4-TRI-TRI-TRI|CIR',
        skill: 'LHT_CRS_2', cost: 34,
    },
    {
        code: 'RFT_GRB',    name: "Royal Fist of Grom Blitz",
        type: WPN_FIST,     material: WOOD,
        score: 1702,        slots: 'ELE_5-SKL_5-REC-STA-TRI|CIR',
        skill: 'LHT_BST_2', cost: 35,
    },
    {
        code: 'NBD_JOY',    name: "Noel Blade of Joyeuse",
        type: WPN_SWORD,    material: IRON,
        score: 3139,        slots: 'ELE_10-HAS_9-CIR-DAI-TRI|CIR',
        skill: 'LHT_RAY_2', limited: true,
        cost: 40,
    },
    {
        code: 'GHD_HDS',    name: "Great Hand of Hades",
        type: WPN_FIST,     material: IRON,
        score: 1808,        slots: 'DRK_9-CIR-REC-TRI-STA|TRI',
        skill: 'LHT_DGN_3', cost: 36,
    },
    {
        code: 'HBW_RET',    name: "Holy Blow of Retia",
        type: WPN_FIST,     material: CRYS,
        score: 1940,        slots: 'ELE_10-HAS_9-TRI-TRI-TRI|DAI',
        skill: 'LHT_BST_3', limited: true,
        cost: 40,
    },
    {
        code: 'HLC_SHU',    name: "Holy Lance of Shutia",
        type: WPN_LANCE,    material: CRYS,
        score: 3113,        slots: 'LHT_10-ATK_10-DEF_10-HP_10-TRI|CIR',
        skill: 'LHT_CRS_3', limited: true,
        cost: 37,
    },
    {
        code: 'HHM_MET',    name: "Holy Hammer of Metia",
        type: WPN_HMMR,     material: IRON,
        score: 2916,        slots: 'FIR_10-HEA_9-DAI-CIR-TRI|TRI',
        skill: 'MTR_STM_3', limited: true,
        cost: 37,
    },
    {
        code: 'HLY_REV',    name: "Holy Revenant",
        type: WPN_FIST,     material: FRAG,
        score: 1516,        slots: 'STA-REC-TRI-CIR-DAI|TRI',
        skill: 'DRN_BST_3', evt: true,
        cost: 38,
    },
    {
        code: 'DSY_VOD',    name: "Dieity Slayer Void",
        type: WPN_SWORD,    material: HORN,
        score: 2938,        slots: 'QUI_4-SKL_5-TRI-CIR-KIT|CIR',
        skill: 'SPD_BMR_2',
        cost: 36,
    },
    {
        code: 'DSY_VNT',    name: "Lance of Deity Slayer Vanitas",
        type: WPN_HMMR,     material: HORN,
        score: 2701,        slots: 'QUI_4-CMB_5-TRI-CIR-TRI|CIR',
        skill: 'SPD_BMR_2', cost: 36,
    },
    {
        code: 'TPS_HVN',    name: "Ultra Tempest of Heaven",
        type: WPN_STAFF,    material: WOOD,
        score: 2803,        slots: 'WND_10-LHT_5-HP_10-TRI-DAI|TRI',
        skill: 'AIR_BST_3', evt: true,
        cost: 37,
    },
    {
        rcode: 3049,    name: "Tempest of Heaven",
        type: WPN_STAFF,    material: WOOD,
        score: 2464,        slots: 'WND_5-LHT_4-HP_5-TRI-DAI|TRI',
        skill: 'AIR_BST_2', evt: true,
        cost: 34,
    },
    {
        code: 'HRD_FJM',    name: "Holy Rod of Frajelm",
        type: WPN_STAFF,    material: IRON,
        score: 2800,        slots: 'ICE_10-HEA_9-SKL_10-TRI-REC|CIR',
        skill: 'ICE_EDG_3', limited: true,
        cost: 37,
    },
    {
        code: 'RTT_SPR',    name: "Ratatoskr Spear",
        type: WPN_LANCE,    material: HORN,
        score: 2866,        slots: 'ELE_5-HAS_5-ATK_5-TRI-TRI|KIT',
        skill: 'LHT_BST_2', cost: 35,
    },
    {
        code: 'HMM_OPM',    name: "Sacred Hammer of the Open Mind",
        type: WPN_HMMR,     material: HORN,
        score: 2761,        slots: 'WND_10-ATK_10-SKL_9-DAI-TRI|DAI',
        skill: 'AIR_BST_2', cost: 36,
    },
    {
        code: 'ICT_FNR',    name: "Ice Tusk of Fenrir",
        type: WPN_FIST,     material: CRYS,
        score: 1637,        slots: 'ICE_5-HAS_4-TRI-TRI-CIR|TRI',
        skill: 'BZD_DGR_2', cost: 35,
    },
    {
        code: 'SRD_LTS',    name: "Sun Rod of Lithosphere",
        type: WPN_STAFF,    material: IRON,
        score: 2574,        slots: 'FIR_10-SKL_10-HEA_9-CIR-TRI|DAI',
        skill: 'BLZ_DGR_2', cost: 36,
    },
    {
        code: 'TPS_ATF',    name: "Tempest Artifact",
        type: WPN_SWORD,    material: CRYS,
        score: 3000,        slots: 'STA-REC-CIR-TRI-DAI|CIR',
        skill: 'SPD_BMR_2', evt: true,
        cost: 36,
    },
    {
        code: 'HWF_IZN',    name: "Holy Wind Fist of Izanagi",
        type: WPN_FIST,     material: WOOD,
        score: 1957,        slots: 'WND_10-QUI_9-SKL_10-CIR-CIR|CIR',
        skill: 'HUG_CYL_3', limited: true,
        cost: 41,
    },
    {
        code: 'AMN_MRK',    name: "Ame no Murakumo",
        type: WPN_SWORD,    material: WOOD,
        score: 3154,        slots: 'LHT_10-HAS_9-CMB_10-TRI-DAI|TRI',
        skill: 'HLY_BST_3', limited: true,
        cost: 41,
    },
    {
        code: 'DVN_LHG',    name: "Divine Lohengrin",
        type: WPN_LANCE,    material: CRYS,
        score: 2725,        slots: 'LHT_3-CIR-TRI-DAI-KIT|CIR',
        skill: 'RAS_BMR_2', limited: true,
        cost: 34,           brave_rate: 1.5,
    },
    {
        code: 'FLC_WDS',    name: "Freyja's Lance of Worldly Desires",
        type: WPN_LANCE,    material: CRYS,
        score: 2776,        slots: 'FIR_9-SKL_9-CMB_4-REC-CIR|DAI',
        skill: 'FLM_BLD_2', evt: true,
        cost: 36,
    },
    {
        code: 'AST_JPT',    name: "Almighty Staff of Jupiter",
        type: WPN_STAFF,    material: CRYS,
        score: 2450,        slots: 'ICE_9-SKA_9-HEA_4-CIR-TRI|CIR',
        skill: 'BZD_DGR_2', evt: true,
        cost: 36,
    },
    {
        code: 'DMC_BGT',    name: "Dark Mace of Brigantia",
        type: WPN_HMMR,     material: IRON,
        score: 2779,        slots: 'DRK_5-SKA_5-TRI-CIR-TRI|DAI',
        skill: 'DRK_DGR_2', cost: 35,
    },
    {
        code: 'IPF_DBL',    name: "Imperial Fist of Dibelius",
        type: WPN_FIST,     material: CRYS,
        score: 1763,        slots: 'LHT_10-HAS_9-ATK_10-CIR-TRI',
        skill: 'STA_DGR_2', cost: 36,
    },
    {
        code: 'ATH_QSP',    name: "Aethereal Queenspike",
        type: WPN_LANCE,    material: HORN,
        score: 2909,        slots: 'HAS_10-CMB_10-TRI-STA-CIR|CIR',
        skill: 'SPD_BMR_2', cost: 35,
    },
    {
        code: 'LGF_TPS',    name: "Landgraff's Tempest",
        type: WPN_HMMR,     material: WOOD,
        score: 2771,        slots: 'WND_10-QUI_9-CMB_10-CIR-TRI|DAI',
        skill: 'HRO_BMR_2', cost: 36,
    },
    {
        code: 'RGC_TPS',    name: "Regenschirm's Tempest",
        type: WPN_STAFF,    material: WOOD,
        score: 2673,        slots: 'WND_10-SKA_9-SKL_10-TRI-KIT|TRI',
        skill: 'AIR_BST_2', cost: 37,
    },
    {
        code: 'DVN_RPR',    name: "Divine Reaper",
        type: WPN_LANCE,    material: CRYS,
        score: 2924,        slots: 'SKL_10-SKA_9-TRI-REC-STA|CIR',
        skill: 'PTN_RAI_2', cost: 36,
    },
    {
        code: 'QET_SPL',    name: "Ultra Queen Ether of Sparklight",
        type: WPN_FIST,     material: CRYS,
        score: 1739,        slots: 'ELE_10-DRK_5-HAS_10-CIR-TRI|TRI',
        skill: 'THD_STM_3', evt: true,
        cost: 37,
    },
    {
        rcode: 3056,    name: "Queen Ether of Sparklight",
        type: WPN_FIST,     material: CRYS,
        score: 1610,        slots: 'ELE_8-DRK_4-HAS_8-CIR-TRI|TRI',
        skill: 'THD_STM_2', evt: true,
        cost: 34,
    },
    {
        code: 'LOV_MOD',    name: "Love a la Mode",
        type: WPN_LANCE,    material: IRON,
        score: 3116,        slots: 'FIR_10-ATK_10-DEF_10-SKL_10-DAI|TRI',
        skill: 'RRY_ETL_3', limited: true,
        cost: 40,
    },
    {
        code: 'VNS_SWD',    name: "Venus's Sword",
        type: WPN_SWORD,    material: IRON,
        score: 3204,        slots: 'HAS_10-CMB_10-SKR_5-TRI-STA|CIR',
        skill: 'MTR_STM_3', limited: true,
        cost: 41,
    },
    {
        code: 'CCL_MDT',    name: "Concealed Malediction",
        type: WPN_LANCE,    material: HORN,
        score: 3000,        slots: 'STA-DAI-CIR-TRI-CIR|CIR',
        skill: 'SPD_BMR_2', evt: true,
        cost: 36,
    },
    {
        code: 'DGF_GET',    name: "Dragon Fist of Getai",
        type: WPN_FIST,     material: HORN,
        score: 1676,        slots: 'ELE_5-HAS_4-TRI-CIR-KIT|DAI',
        skill: 'LTB_LNC_2', limited: true,
        cost: 36,
    },
    {
        code: 'DBL_CHN',    name: "Dragon Blade Cthonios",
        type: WPN_SWORD,    material: HORN,
        score: 3039,        slots: 'ELE_5-SKA_4-TRI-CIR-DAI|TRI',
        skill: 'UTR_DCH_2', limited: true,
        cost: 36,
    },
    {
        code: 'SML_GZR',    name: "Shadow Mallet Grand Zero",
        type: WPN_HMMR,     material: IRON,
        score: 2670,        slots: 'DRK_5-SKL_3-CIR-DAI-TRI|CIR',
        skill: 'LVA_FLM_2', evt: true,
        cost: 34,
    },
    {
        code: 'GBT_STF',    name: "Ganbanteinn Staff",
        type: WPN_STAFF,    material: CRYS,
        score: 2582,        slots: 'LHT_4-LHT_3-SKA_4-CIR-TRI|TRI',
        skill: 'HLY_BST_2', cost: 35,
    },
    {
        code: 'TSW_JBR',    name: "Tempest Sword Jibril",
        type: WPN_SWORD,    material: CRYS,
        score: 2787,        slots: 'WND_5-HAS_3-TRI-CIR-TRI|CIR',
        skill: 'GAL_ARW_2', cost: 34,
    },
    {
        code: 'SCB_ASN',    name: "Scorched Blade Asthenosphere",
        type: WPN_SWORD,    material: WOOD,
        score: 2973,        slots: 'FIR_5-SKL_5-TRI-TRI-REC|CIR',
        skill: 'PHO_RAI_2', cost: 35,
    },
    {
        code: 'HSP_VLC',    name: "Holy Spear of Valcan",
        type: WPN_LANCE,    material: WOOD,
        score: 2741,        slots: 'FIR_5-SKL_4-KIT-CIR-TRI|CIR',
        skill: 'PHO_RAI_2', cost: 34,
    },
    {
        code: 'STF_SCT',    name: "Staff of Scintilla",
        type: WPN_STAFF,    material: IRON,
        score: 2469,        slots: 'ELE_5-SKA_3-TRI-TRI-TRI|CIR',
        skill: 'THD_BLT_2', cost: 34,
    },
    {
        code: 'GAE_BLG',    name: "Gae Bolg",
        type: WPN_LANCE,    material: IRON,
        score: 2681,        slots: 'LHT_5-SKG_3-TRI-CIR-KIT|CIR',
        skill: 'LHT_CRS_2', cost: 34,
    },
    {
        code: 'LCB_BLD',    name: "Iceberg Blade",
        type: WPN_SWORD,    material: IRON,
        score: 2872,        slots: 'ICE_3-ICE_3-HAS_3-DAI-CIR|TRI',
        skill: 'ICE_EDG_2', cost: 34,
    },
    {
        code: 'TTR_DRK',    name: "Tartaros Fist of Darkness",
        type: WPN_FIST,     material: CRYS,
        score: 1735,        slots: 'DRK_5-HAS_5-TRI-CIR-TRI',
        skill: 'DRK_GZR_2', cost: 35,
    },
    {
        code: 'ICF_SCN',    name: "Ice Fist Schneeregen",
        type: WPN_FIST,     material: CRYS,
        score: 1570,        slots: 'ICE_5-HAS_3-DAI-CIR-TRI|TRI',
        skill: 'ICE_EDG_2', cost: 34,
    },
    {
        code: 'CLW_NTR',    name: "Claw of the Night Terror",
        type: WPN_FIST,     material: HORN,
        score: 1794,        slots: 'DRK_10-CMB_10-HAS_9-CIR-TRI|DAI',
        skill: 'DRK_MTR_2', cost: 41,
    },
    {
        code: 'WND_NTR',    name: "Wand of the Night Terror",
        type: WPN_STAFF,    material: HORN,
        score: 2704,        slots: 'WND_10-SKL_10-QUI_9-TRI-DAI|CIR',
        skill: 'TPS_RAI_2',
        cost: 39,
    },
    {
        code: 'TLV_VSR',    name: "True Love's Vow of Sarah",
        type: WPN_LANCE,    material: IRON,
        score: 2780,        slots: 'LHT_9-HEA_9-SKA_4-TRI-CIR|CIR',
        skill: 'DBL_BMR_2', evt: true,
        cost: 34,
    },
    {
        code: 'FNG_FST',    name: "Fanged Flagstaff",
        type: WPN_LANCE,    material: HORN,
        score: 3108,        slots: 'LHT_10-HAS_10-CMB_10-CIR-CIR|TRI',
        skill: 'LHT_CRS_3', limited: true,
        cost: 36,
    },
    {
        code: 'EPN_MLD',    name: "Euphonium's Melody",
        type: WPN_STAFF,    material: CRYS,
        score: 2838,        slots: 'ELE_10-SKL_10-SKG_10-CIR-CIR|TRI',
        skill: 'LHT_DGR_3', limited: true,
        cost: 36,
    },
    {
        code: 'HEX_DYN',    name: "Hexed Dynslave",
        type: WPN_SWORD,    material: FRAG,
        score: 1764,        slots: 'STA-DAI-CIR-TRI',
        skill: 'RAS_BMR_2', evt: true,
        cost: 32,           rank: RANK_S,
    },
    {
        code: 'XXX_NVN',    name: "Blessed Nirvana",
        type: WPN_STAFF,    material: FRAG,
        score: 1819,        slots: 'STA-KIT-CIR-CIR-TRI',
        skill: 'MTR_STM_2', evt: true,
        cost: 32,           rank: RANK_S,
    },
    {
        code: 'DMD_DML',    name: "Doomed Darkmaul",
        type: WPN_HMMR,     material: FRAG,
        score: 2727,        slots: 'TRI-TRI-CIR-STA-DAI|CIR',
        skill: 'DRK_GZR_2', evt: true,
        cost: 34,
    },
    {
        code: 'FST_SGD',    name: "Fist of the Stargrinder",
        type: WPN_FIST,     material: IRON,
        score: 1968,        slots: 'ICE_10-ELF_5-SKR_5-CIR-CIR|TRI',
        skill: 'BLZ_RAI_3', limited: true,
        cost: 35,
    },
    {
        code: 'ATR_QSL',    name: "Aethereal Queenslayer",
        type: WPN_SWORD,    material: IRON,
        score: 2953,        slots: 'HAS_10-CMB_10-TRI-STA-CIR|TRI',
        skill: 'DVL_CLW_2',
        cost: 35,
    },
    {
        code: 'RAY_CXT',    name: "Ray Cluxta Mace",
        type: WPN_HMMR,     material: CRYS,
        score: 2733,        slots: 'SKL_10-QUI_8-SKA_8-TRI-TRI|TRI',
        skill: 'HRO_BMR_2',
        cost: 36,
    },
    {
        code: 'NOV_CXR',    name: "Nova Cluxta Rod",
        type: WPN_STAFF,    material: CRYS,
        score: 2623,        slots: 'ICE_10-COU_5-SKL_9-HP_9-REC|TRI',
        skill: 'BZD_DGR_2',
        cost: 37,
    },
    {
        code: 'FST_DET',    name: "Fist of the Darkeater",
        type: WPN_FIST,     material: CRYS,
        score: 1802,        slots: 'SKL_10-HAS_10-CIR-REC-STA|TRI',
        skill: 'SPD_BMR_2', cost: 38,
    },
    {
        code: 'FAL_FBK',    name: "Falling Full Break",
        type: WPN_HMMR,     material: IRON,
        score: 3000,        slots: 'STA-DAI-CIR-REC-CIR|CIR',
        skill: 'SPD_BMR_2', evt: true,
        cost: 36,
    },
    {
        code: 'RSN_SPB',    name: "Divine Edge Rasen Sparkbolt",
        type: WPN_SWORD,    material: WOOD,
        score: 2976,        slots: 'ELE_10-HAS_10-QUI_9-CIR-TRI|TRI',
        skill: 'LHT_RAI_2', cost: 35,
    },
    {
        code: 'CLT_PTS',    name: "Lance of Celestial Phantasm",
        type: WPN_LANCE,    material: WOOD,
        score: 3000,        slots: 'DRK_10-HAS_9-EFR_5-CIR-CIR|CIR',
        skill: 'DRK_MTR_2', cost: 50,
    },
    {
        code: 'IFN_HCT',    name: "Inferno Lance Hell-Castor",
        type: WPN_LANCE,    material: HORN,
        score: 2711,        slots: 'FIR_9-DRK_9-SKL_9-CIR-REC|CIR',
        skill: 'PHO_RAI_2', evt: true,
        cost: 34,
    },
    {
        code: 'FBW_DMS',    name: "Forbidden Blow Deimos",
        type: WPN_FIST,     material: IRON,
        score: 1912,        slots: 'HAS_10-QUI_8-EFR_5-TRI-STA|CIR',
        skill: 'HRO_BMR_3', limited: true,
        cost: 50,
    },
    {
        code: 'SSR_LGN',    name: "Samsara Lance Longinus",
        type: WPN_LANCE,    material: IRON,
        score: 3115,        slots: 'HAS_10-QUI_8-EFR_5-TRI-STA|TRI-CIR',
        skill: 'LHT_DGN_3', limited: true,
        cost: 50,
    },
    {
        code: 'RCN_MAC',    name: "Royal Chronos Mace",
        type: WPN_HMMR,     material: WOOD,
        score: 2775,        slots: 'LHT_10-CMB_10-ATK_9-QUI_8-KIT|DAI',
        skill: 'JDM_RAI_2', cost: 36,
    },
    {
        code: 'STL_ALL',    name: "Sanct-Talon Alabastrine",
        type: WPN_FIST,     material: WOOD,
        score: 1822,        slots: 'WND_10-HAS_9-EFR_5-TRI-KIT|TRI',
        skill: 'TND_DGR_2', cost: 37,
    },
    {
        code: 'BLT_DMC',    name: "Blighted Damocles",
        type: WPN_SWORD,    material: FRAG,
        score: 2925,        slots: 'TRI-TRI-CIR-REC-TRI|TRI',
        skill: 'SPD_BMR_3', evt: true,
        cost: 35,
    },
    {
        code: 'LDC_AJT',    name: "Ultra Lightdrake's Claw Absolut-Justitia",
        type: WPN_FIST,     material: HORN,
        score: 1754,        slots: 'LHT_10-DRK_5-SKL_10-CIR-REC|TRI',
        skill: 'HVN_RAI_3', evt: true,
        cost: 37,
    },
    {
        rcode: 3070,    name: "Lightdrake's Claw Absolut-Justitia",
        type: WPN_FIST,     material: HORN,
        score: 1660,        slots: 'LHT_8-DRK_4-SKL_8-CIR-REC|TRI',
        skill: 'HVN_RAI_2', evt: true,
        cost: 34,
    },
    {
        code: 'BAL_BLD',    name: "Brilliant Alexander Blade",
        type: WPN_SWORD,    material: CRYS,
        score: 3000,        slots: 'EFR_5-HAS_10-TRI-TRI-STA|TRI',
        skill: 'HRO_BMR_2', cost: 36,
    },
    {
        code: 'RAL_LNC',    name: "Radiant Alexandria Lance",
        type: WPN_LANCE,    material: CRYS,
        score: 2980,        slots: 'DRK_10-QUI_9-SKL_10-CIR-DAI|TRI',
        skill: 'GVT_FLD_2', cost: 37,
    },
    {
        code: 'ANG_LUS',    name: "Aerial Skyheart",
        type: WPN_STAFF,    material: IRON,
        score: 2760,        slots: 'LHT_10-SKA_10-EFR_5-CIR-TRI|REC',
        skill: 'SHN_ARW_3', cost: 38,
        limited: true,
    },
    {
        code: 'STL_ECL',    name: "Starlight Eclipser",
        type: WPN_LANCE,    material: CRYS,
        score: 1688,        slots: 'ICE_3-ICE_3-REC-CIR-DAI',
        skill: 'ICE_EDG_1', cost: 33,
        evt: true,          rank: RANK_S,
    },
    {
        code: 'FSS_STF',    name: "Forseti's Spirit Staff",
        type: WPN_STAFF,    material: WOOD,
        score: 1510,        slots: 'WND_4-SKA_3-STA-TRI-CIR',
        skill: 'SPR_AIR_1', cost: 32,
        limited: true,      rank: RANK_S,
    },
    {
        code: 'NTL_CMS',    name: "Ninetail's Crimsonfury",
        type: WPN_FIST,     material: HORN,
        score: 1970,        slots: 'FIR_10-HAS_10-EFR_5-KIT-DAI|TRI',
        skill: 'IFN_RAI_3', cost: 41,
        limited: true,
    },
    {
        code: 'NTL_ROD',    name: "Immortal Ninetail's Rod",
        type: WPN_STAFF,    material: HORN,
        score: 2876,        slots: 'ELE_10-SKL_10-SKR_5-REC-CIR|CIR',
        skill: 'LHT_DOO_3', cost: 42,
        limited: true,
    },
    {
        code: 'DMN_BRD',    name: "Demon's Beard",
        type: WPN_SWORD,    material: IRON,
        score: 1720,        slots: 'SKG_3-HAS_3-STA-CIR-CIR',
        skill: 'MTR_STM_1', cost: 32,
        limited: true,      rank: RANK_S,
    },
    {
        code: 'MAC_DET',    name: "Mace of the Darkeater",
        type: WPN_HMMR,     material: IRON,
        score: 2800,        slots: 'DRK_10-KOH_5-QUI_9-TRI-TRI|TRI',
        skill: 'DRK_MTR_2', cost: 36,
        brave_rate: 5,
    },
    {
        code: 'QUE_VLC',    name: "Queen of Valience",
        type: WPN_FIST,     material: HORN,
        score: 1830,        slots: 'WND_10-SKL_10-CMB_10-CIR-REC|DAI',
        skill: 'HUG_CYL_4', cost: 40,
    },
    {
        code: 'EXM_BLD',    name: "Ex Machina Blade",
        type: WPN_SWORD,    material: IRON,
        score: 3000,        slots: 'FIR_10-HAS_10-EFR_4-CIR-CIR|TRI',
        skill: 'MTR_STM_2', cost: 35,
    },
    {
        code: 'MCX_HMR',    name: "Machina Xeta Hammer",
        type: WPN_HMMR,     material: IRON,
        score: 2900,        slots: 'ELE_10-FUR_5-SPB_4-CIR-CIR|TRI',
        skill: 'LHT_DGR_2', cost: 37,
    },
    {
        code: 'MTO_PMN',    name: "Meteoroid Prominence",
        type: WPN_FIST,     material: CRYS,
        score: 2000,        slots: 'WND_10-SPB_5-EFR_4-CIR-REC|TRI',
        skill: 'TND_DGR_3', cost: 42,
        limited: true,
    },
    {
        code: 'MTO_PMN',    name: "Omega Dragonmaul",
        type: WPN_HMMR,     material: FRAG,
        score: 3000,        slots: 'TRI-REC-CIR-CIR-STA|TRI',
        skill: 'HRO_BMR_3', cost: 40,
        limited: true,
    },
    {
        code: 'TDH_BDG',    name: "Thunderhead Blundgeon",
        type: WPN_HMMR,     material: IRON,
        score: 2911,        slots: 'ELE_10-ATK_10-SPB_4-TRI-CIR|CIR',
        skill: 'LHT_DOO_2', cost: 37,
    },
    {
        code: 'SPK_SCT',    name: "Sprocket Scepter",
        type: WPN_STAFF,    material: IRON,
        score: 2700,        slots: 'LHT_10-QUI_10-EFR_4-CIR-DAI|TRI',
        skill: 'STA_DGR_2', cost: 37,
    },
    {
        code: 'SCS_HLT',    name: "Sacred Seed of the Holy Tree",
        type: WPN_HMMR,     material: WOOD,
        score: 2700,        slots: 'LHT_10-EFR_3-SKA_8-TRI-CIR',
        skill: 'HLY_SAN_2', cost: 34,
        evt: true,
    },
    {
        code: 'SSN_SUP',    name: "Sizzling Sunny-Side Up",
        type: WPN_HMMR,     material: FRAG,
        score: 2800,        slots: 'TRI-TRI-CIR-CIR-REC|TRI',
        skill: 'RIS_SUN_2', cost: 24,
        evt: true,
    },
    {
        code: 'EVT_ERD',    name: "Elan Vital de Eurydike",
        type: WPN_FIST,     material: WOOD,
        score: 1850,        slots: 'HAS_10-QUI_10-EFR_4-DAI-STA|TRI',
        skill: 'WLD_BRK_3', cost: 40,
    },
    {
        code: 'MDB_DEA',    name: "Medjed's Blade of the Dead",
        type: WPN_SWORD,    material: FRAG,
        score: 3247,        slots: 'DRK_10-EFR_5-QUI_10-CIR-DAI|TRI',
        skill: 'DRK_DGR_3', cost: 48,
        limited: true,
    },
    {
        code: 'MDL_DEA',    name: "Medjed's Lance of the Dead",
        type: WPN_LANCE,    material: FRAG,
        score: 3127,        slots: 'ICE_10-EFR_5-HAS_10-CIR-TRI|CIR',
        skill: 'GLC_WHO_3', cost: 48,
        limited: true,
    },
    {
        rcode: 3094,        name: "Silver Imperial Edge",
        type: WPN_SWORD,    material: HORN,
        score: 3010,        slots: 'FIR_10-EFR_4-HAS_10-TRI-TRI|CIR',
        skill: 'CLT_FLA_2', cost: 41,
    },
    {
        rcode: 3105,        name: "Ultimate Rod of the Pharoah",
        type: WPN_STAFF,    material: FRAG,
        score: 2570,        slots: 'TRI-DAI-CIR-REC-KIT|TRI',
        skill: 'JDM_RAI_2', cost: 36,
        evt: true,
    },
    {
        rcode: 3093,        name: "Silver Imperial Rod",
        type: WPN_STAFF,    material: HORN,
        score: 2780,        slots: 'LHT_10-SKA_10-EFR_4-CIR-REC|TRI',
        skill: 'WLD_BRK_3', cost: 38,
    },
    {
        rcode: 3086,        name: "Imperial Belial Zyne",
        type: WPN_SWORD,    material: IRON,
        score: 2850,        slots: 'DRK_10-ELE_4-SKL_9-DAI-REC|CIR',
        skill: 'MTR_STM_3', cost: 38,
        evt: true,
    },
    {
        rcode: 3096,        name: "Crescent Dragoner's Claw",
        type: WPN_FIST,     material: IRON,
        score: 1975,        slots: 'ICE_10-CMB_10-HRF_5-REC-TRI|CIR',
        skill: 'BZD_DGR_3', cost: 41,
        limited: true,
    },
    {
        rcode: 3105,        name: "Blooming Lygodium Lance",
        type: WPN_LANCE,    material: WOOD,
        score: 2720,        slots: 'WND_9-LHT_4-HAS_9-CIR-CIR',
        skill: 'STM_CAG_2', cost: 0,
        evt: true,
    },
    {
        rcode: 3095,        name: "Dragoner's Crescent Piercer",
        type: WPN_LANCE,    material: IRON,
        score: 3135,        slots: 'ELE_10-QUI_10-HRF_5-TRI-CIR|TRI',
        skill: 'LHN_VTX_3', cost: 43,
        limited: true,
    },
    {
        rcode: 1080,        name: "Queen Aphrodite's Ice Wand",
        type: WPN_STAFF,    material: WOOD,
        score: 2780,        slots: 'SKA_10-ICE_10-ADH_4-KIT-TRI|TRI',
        skill: 'ICE_EDG_4', cost: 40,
    },
    {
        rcode: 3023,        name: "Supreme Kaizer Knuckle",
        type: WPN_FIST,     material: IRON,
        score: 2000,        slots: 'REC-TRI-CIR-CIR-CIR|CIR',
        skill: 'WLD_BRK_2', cost: 100,
        evt: true,
    },
    {
        rcode: 3110,        name: "Gallant Claw of Gouki",
        type: WPN_FIST,     material: WOOD,
        score: 2000,        slots: 'KOH_6-HRF_5-EFR_5-STA-TRI|CIR',
        skill: 'BDL_BMR_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3109,        name: "Mortal Blade of Yasha",
        type: WPN_SWORD,    material: WOOD,
        score: 3250,        slots: 'WND_10-SPB_5-KOH_6-TRI-CIR|TRI',
        skill: 'TPS_RAI_3', cost: 50,
        limited: true,
    },
    {
        rcode: 1133,        name: "Cursed Fist Grimorspike",
        type: WPN_FIST,     material: CRYS,
        score: 1900,        slots: 'FIR_10-HTF_5-EFR_4-CIR-TRI|REC',
        skill: 'BLZ_DGR_2', cost: 45,
    },
    {
        rcode: 1134,        name: "Cobalt Gullinkambi Sword",
        type: WPN_SWORD,    material: CRYS,
        score: 3100,        slots: 'LHT_10-SPB_5-EFR_4-REC-TRI|CIR',
        skill: 'STA_DGR_2', cost: 45,
    },
    {
        rcode: 9023,        name: "Cube of Fortune",
        type: WPN_FIST,     material: IRON,
        score: 1700,        slots: 'SKR_5-HRF_3-TRI-CIR-REC|CIR',
        skill: 'LHT_DGN_2', cost: 37,
        evt: true,
    },
    {
        rcode: 1135,        name: "Alea Fortuna Lance",
        type: WPN_LANCE,    material: IRON,
        score: 3007,        slots: 'FIR_10-SPB_5-HRF_4-TRI-TRI|DAI',
        skill: 'EDG_IFN_3', cost: 45,
    },
    {
        rcode: 1136,        name: "Alea Fortuna Rod",
        type: WPN_STAFF,    material: IRON,
        score: 2790,        slots: 'ELE_10-EFR_4-SKG_10-TRI-REC',
        skill: 'LHT_DOO_2', cost: 0,
    },
    {
        rcode: 3006,        name: "Phantasm Blade Murasame",
        type: WPN_SWORD,    material: WOOD,
        score: 3135,        slots: 'SKG_10-HAS_10-KOH_4-EFR_3-REC|STA',
        skill: 'DRN_BST_2', cost: 43,
    },
    {
        rcode: 3089,        name: "Adamant Cerulean Lance",
        type: WPN_LANCE,    material: CRYS,
        score: 3013,        slots: 'HRF_5-QUI_10-EFR_4-CIR-REC|TRI',
        skill: 'BDL_BMR_2', cost: 45,
    },
    {
        rcode: 3090,        name: "Adamant Cerulean Mace",
        type: WPN_HMMR,     material: CRYS,
        score: 2970,        slots: 'ICE_10-SPB_5-EFR_5-TRI-REC|CIR',
        skill: 'BLZ_RAI_3', cost: 42,
    },
    {
        rcode: 9026,        name: "Primordial Blaze",
        type: WPN_STAFF,    material: CRYS,
        score: 2548,        slots: 'FIR_10-SKA_9-ELF_5-CIR-TRI|CIR',
        skill: 'CLT_FLA_2', cost: 36,
        evt: true,
    },
    {
        rcode: 1501,        name: "Lord of Dusk",
        type: WPN_FIST,     material: FRAG,
        score: 1763,        slots: 'CIR-TRI-REC-TRI-REC|DAI',
        skill: 'GVT_FLD_3', cost: 41,
        evt: true,
    },
    {
        rcode: 3091,        name: "Phenomenal Machanic Glove",
        type: WPN_FIST,     material: WOOD,
        score: 1930,        slots: 'FIR_10-EFR_5-HRF_4-QUI_9-DAI|STA',
        skill: 'WLD_END_3', cost: 45,
    },
    {
        rcode: 3101,        name: "Tempest Dragon Lance Adaraxia",
        type: WPN_LANCE,    material: HORN,
        score: 2824,        slots: 'ICE_10-ELE_9-EFR_4-TRI-REC|DAI',
        skill: 'FZR_BTH_3', cost: 38,
        evt: true,
    },
    {
        rcode: 3097,        name: "Lucifer's Fallen Staff",
        type: WPN_STAFF,    material: IRON,
        score: 2800,        slots: 'ELE_10-CMB_10-MGR_5-REC-TRI|TRI',
        skill: 'THD_STM_3', cost: 40,
    },
    {
        rcode: 9027,        name: "Luminaritus",
        type: WPN_SWORD,    material: HORN,
        score: 2925,        slots: 'LHT_10-WND_9-SPB_3-TRI-CIR|REC',
        skill: 'PTN_RAI_2', cost: 35,
        evt: true,
    },
    {
        rcode: 3107,        name: "Ballistic Battering Ram",
        type: WPN_LANCE,    material: HORN,
        score: 3000,        slots: 'MGR_5-HRF_5-CMB_10-CIR-TRI|STA-CIR',
        skill: 'SAB_WTH_3', cost: 50,
    },
    {
        rcode: 1502,        name: "Tactical Tomahawk",
        type: WPN_SWORD,    material: HORN,
        score: 3200,        slots: 'TMV_5-SPB_5-SKL_10-STA-CIR|TRI-TRI',
        skill: 'SAB_WTH_3', cost: 50,
    },
    {
        rcode: 3111,        name: "Ominous Evil Knight",
        type: WPN_LANCE,    material: CRYS,
        score: 3006,        slots: 'SSL_5-MGR_5-SKA_10-TRI-CIR|REC-TRI',
        skill: 'SAB_WTH_3', cost: 45,
    },
    {
        rcode: 3098,        name: "Lucifer's Fallen Blow",
        type: WPN_HMMR,     material: CRYS,
        score: 2950,        slots: 'DRK_10-QUI_9-EFR_5-DAI-TRI|CIR',
        skill: 'DRK_TRD_2', cost: 39,
    },
    {
        rcode: 3112,        name: "Ominous Knight Brawler",
        type: WPN_HMMR,     material: CRYS,
        score: 2970,        slots: 'SPB_5-EFR_5-CMB_10-CIR-DAI|KIT-CIR',
        skill: 'SAB_WTH_3', cost: 42,
    },
    {
        rcode: 3104,        name: "Chord Ripper AΩ",
        type: WPN_LANCE,    material: WOOD,
        score: 2865,        slots: 'WND_10-HEA_10-CIR-TRI-REC|CIR',
        skill: 'TND_DGR_2', cost: 44,
        evt: true,
    },
    {
        rcode: 3071,        name: "Rod of Caustic Doom",
        type: WPN_STAFF,    material: IRON,
        score: 2950,        slots: 'EFR_6-SPB_5-MGR_5-CIR-DAI|TRI-REC',
        skill: 'ETR_WAV_3', cost: 50,
        limited: true,
    },
    {
        rcode: 9028,        name: "Sparked Bulldog",
        type: WPN_HMMR,     material: WOOD,
        score: 2794,        slots: 'FIR_10-QUI_9-KOH_3-CIR-TRI|REC',
        skill: 'RIS_SUN_2', cost: 30,
        evt: true,
    },
    {
        rcode: 1500,        name: "Doomed Revenant",
        type: WPN_LANCE,    material: FRAG,
        score: 2800,        slots: 'REC-CIR-TRI-REC-REC|REC',
        skill: 'SPD_BMR_2', cost: 38,
        evt: true,
    },
    {
        rcode: 9033,        name: "Prism Bravetronic Mic",
        type: WPN_STAFF,    material: WOOD,
        score: 3000,        slots: 'STA-CIR-TRI-TRI-REC|CIR',
        skill: 'WLD_BRK_3', cost: 44,
        evt: true,
    },
    {
        rcode: 3072,        name: "Caustic Glove of Destruction",
        type: WPN_FIST,     material: IRON,
        score: 2079,        slots: 'EFR_6-EFR_5-TMV_5-CIR-REC|DAI-CIR',
        skill: 'SAB_WTH_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3100,        name: "Grand Masquerade",
        type: WPN_STAFF,    material: CRYS,
        score: 2650,        slots: 'EFR_5-KOH_3-QUI_9-CIR-TRI|CIR',
        skill: 'ETR_WAV_2', cost: 42,
        evt: true,
    },
    {
        rcode: 3115,        name: "Lancea Lapin Fortuna",
        type: WPN_LANCE,    material: WOOD,
        score: 3007,        slots: 'LHT_10-WLW_5-HRF_5-TRI-TRI|CIR',
        skill: 'STA_DGR_3', cost: 45,
    },
    {
        rcode: 3084,        name: "Blow of Guilt",
        type: WPN_FIST,     material: IRON,
        score: 1700,        slots: 'HAS_10-QUI_8-MSM_4-DAI-KIT|DAI',
        skill: 'WLD_BRK_3', cost: 44,
        evt: true,
    },
    {
        rcode: 3105,        name: "Necromancer's Shadowstrike",
        type: WPN_FIST,     material: HORN,
        score: 1960,        slots: 'ASM_5-SPB_5-SPS_5-CIR-TRI|CIR',
        skill: 'DRN_BST_3', cost: 42,
    },
    {
        rcode: 3106,        name: "Dark Necromancer's Rod",
        type: WPN_STAFF,    material: HORN,
        score: 2830,        slots: 'ELE_10-MGR_5-HWL_5-CIR-REC|DAI',
        skill: 'LHT_DOO_3', cost: 42,
    },
    {
        rcode: 3092,        name: "Mecha Gavel Flint",
        type: WPN_HMMR,     material: WOOD,
        score: 3150,        slots: 'EFR_6-SOG_6-SPB_5-CIR-DAI|TRI',
        skill: 'SAB_WTH_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3136,        name: "Sapient Penemue Glove",
        type: WPN_FIST,     material: CRYS,
        score: 2083,        slots: 'ELE_11-HRF_6-TMV_5-TRI-REC|CIR',
        skill: 'LHT_DGR_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3135,        name: "Sapient Penemue Rod",
        type: WPN_STAFF,    material: CRYS,
        score: 3050,        slots: 'ICE_11-EFR_6-MGR_5-TRI-TRI|CIR',
        skill: 'ICB_EDG_3', cost: 50,
        limited: true,
    },
    {
        rcode: 9029,        name: "Thunder Strike",
        type: WPN_HMMR,     material: IRON,
        score: 2750,        slots: 'ELE_10-SKA_5-KOH_4-STA-DAI|CIR',
        skill: 'LHT_DGR_3', cost: 40,
        evt: true,
    },
    {
        rcode: 3118,        name: "Animus Honoris Claw",
        type: WPN_FIST,     material: CRYS,
        score: 2140,        slots: 'TMV_6-SOG_6-HWL_6-CIR-STA|CIR',
        skill: 'PGT_FLM_3', cost: 45,
        limited: true,
    },
    {
        rcode: 3119,        name: "Pierce of the Vanquisher",
        type: WPN_LANCE,    material: HORN,
        score: 3050,        slots: 'FIR_10-HWL_6-TMV_5-CIR-TRI|REC-TRI',
        skill: 'PGT_FLM_3', cost: 45,
    },
    {
        rcode: 3120,        name: "Sword of the Vanquisher",
        type: WPN_SWORD,    material: HORN,
        score: 3210,        slots: 'FIR_10-HRF_6-MGR_5-TRI-DAI|CIR',
        skill: 'PGT_FLM_3', cost: 45,
    },
    {
        rcode: 1067,        name: "Crimson Dragon's Fury",
        type: WPN_FIST,     material: CRYS,
        score: 1990,        slots: 'KOH_6-SRS_5-TMV_5-CMB_10-REC',
        skill: 'LHT_DGN_3', cost: 42,
    },
    {
        rcode: 3117,        name: "Virtus Honoris Rod",
        type: WPN_STAFF,    material: HORN,
        score: 3138,        slots: 'MGR_6-HWL_6-KOH_6-TRI-STA|CIR-CIR',
        skill: 'SAB_WTH_4', cost: 42,
        limited: true,
    },
    {
        rcode: 3130,        name: "Elven Etherlight Blow",
        type: WPN_FIST,     material: WOOD,
        score: 1987,        slots: 'LHT_10-TMV_6-TMV_5-CIR-TRI|REC',
        skill: 'JDM_RAI_3', cost: 45,
    },
    {
        rcode: 3129,        name: "Elven Elear Rod",
        type: WPN_STAFF,    material: WOOD,
        score: 2874,        slots: 'FIR_10-MGR_6-SOG_5-CIR-TRI|TRI',
        skill: 'PGT_FLM_3', cost: 45,
    },
    {
        rcode: 1137,        name: "Giant King of Dusk",
        type: WPN_LANCE,    material: FRAG,
        score: 2900,        slots: 'REC-CIR-TRI-CIR-REC|TRI',
        skill: 'WLD_BRK_3', cost: 44,
        evt: true,
    },
    {
        rcode: 3125,        name: "Ultra Galactical Glove",
        type: WPN_FIST,     material: WOOD,
        score: 1750,        slots: 'SOG_5-DSM_5-KOH_5-TRI-REC|CIR',
        skill: 'ETR_WAV_3', cost: 44,
        evt: true,
    },
    {
        rcode: 3116,        name: "Gladius Lapin Fortuna",
        type: WPN_SWORD,    material: WOOD,
        score: 3350,        slots: 'TMV_6-HRF_6-SSL_6-TRI-CIR|TRI',
        skill: 'SAB_WTH_4', cost: 45,
        limited: true,
    },
    {
        rcode: 9016,        name: "Spear of Valhalla",
        type: WPN_LANCE,    material: IRON,
        score: 3200,        slots: 'WLW_6-MGR_6-HRF_5-CIR-TRI|TRI-CIR',
        skill: 'FRJ_DVW_3', cost: 50,
        limited: true,
    },
    {
        rcode: 9017,        name: "Ragnar's Battle Axe",
        type: WPN_HMMR,     material: IRON,
        score: 3180,        slots: 'SOG_6-EFR_6-MGR_5-CIR-TRI|DAI-REC',
        skill: 'MJR_RAG_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3126,        name: "Ultra Katana Galactica",
        type: WPN_SWORD,    material: WOOD,
        score: 3100,        slots: 'DRK_10-LHT_10-HWL_5-REC-CIR',
        skill: 'DRK_MTR_3', cost: 44,
        evt: true,
    },
    {
        rcode: 1138,        name: "Courage Imperial",
        type: WPN_LANCE,    material: HORN,
        score: 3210,        slots: 'TMV_6-EFR_6-HWL_6-CIR-STA|DAI-TRI',
        skill: 'SAB_WTH_4', cost: 45,
        limited: true,
    },
    {
        rcode: 3133,        name: "Flamme Epee en Rouge",
        type: WPN_SWORD,    material: HORN,
        score: 3200,        slots: 'FIR_10-SPB_6-HWL_5-CIR-KIT|DAI',
        skill: 'PGT_FLM_3', cost: 45,
    },
    {
        rcode: 3134,        name: "Flamme Marteau en Rouge",
        type: WPN_HMMR,     material: HORN,
        score: 3020,        slots: 'FIR_10-EFR_6-SPB_5-KIT-CIR|CIR',
        skill: 'PGT_FLM_3', cost: 45,
    },
    {
        rcode: 1508,        name: "Grand Palomides Anima",
        type: WPN_LANCE,    material: IRON,
        score: 3220,        slots: 'SPB_6-HWL_6-WLW_6-TRI-STA|CIR-STA',
        skill: 'CSM_IMP_4', cost: 50,
        limited: true,
    },
    {
        rcode: 3131,        name: "Celeste Gladius",
        type: WPN_SWORD,    material: IRON,
        score: 3215,        slots: 'ICE_11-LHT_10-SPB_5-TRI-TRI|CIR',
        skill: 'ICB_EDG_3', cost: 45,
    },
    {
        rcode: 3132,        name: "Celeste Ephemeral",
        type: WPN_STAFF,    material: IRON,
        score: 3000,        slots: 'LHT_10-SOG_5-MGR_6-CIR-TRI|REC',
        skill: 'FRJ_DVW_3', cost: 45,
    },
    {
        rcode: 3085,        name: "Chaos Rod Ferrum-Alma",
        type: WPN_STAFF,    material: IRON,
        score: 2700,        slots: 'DRK_10-FIR_10-SPB_5-TRI-CIR|TRI',
        skill: 'RIS_DRK_3', cost: 44,
        evt: true,
    },
    {
        rcode: 1510,        name: "Ethereal Guiding Lamp",
        type: WPN_STAFF,    material: WOOD,
        score: 3250,        slots: 'SPB_6-HWL_6-EFR_6-CIR-STA|CIR-TRI',
        skill: 'CSM_IMP_4', cost: 50,
        limited: true,
    },
    {
        rcode: 3124,        name: "Gallivant Viage Blade",
        type: WPN_SWORD,    material: WOOD,
        score: 3220,        slots: 'LHT_10-SPB_6-SOG_5-CIR-REC|KIT',
        skill: 'JDM_RAI_3', cost: 45,
    },
    {
        rcode: 3123,        name: "Jaunting Viage Lance",
        type: WPN_LANCE,    material: WOOD,
        score: 3100,        slots: 'ICE_10-TMV_5-HWL_6-CIR-TRI|CIR-TRI',
        skill: 'ICB_EDG_3', cost: 45,
    },
    {
        rcode: 1139,        name: "Blade of the Peacemaker",
        type: WPN_SWORD,    material: CRYS,
        score: 3450,        slots: 'SPB_6-HWL_6-HRF_6-CIR-STA|CIR-TRI',
        skill: 'CSM_IMP_4', cost: 50,
        limited: true,
    },
    {
        rcode: 3141,        name: "Crimson Siege Lance",
        type: WPN_LANCE,    material: CRYS,
        score: 3250,        slots: 'ICE_11-WND_10-TMV_6-TRI-TRI|CIR-CIR',
        skill: 'WTH_HDS_1', cost: 45,
        limited: true,
    },
    {
        rcode: 1507,        name: "Crimson Siege Bruiser",
        type: WPN_FIST,     material: CRYS,
        score: 2200,        slots: 'FIR_10-HRF_6-MGR_6-CIR-TRI|STA-KIT',
        skill: 'PGT_FLM_4', cost: 45,
        limited: true,
    },
    {
        rcode: 1504,        name: "Siren's Shining Striker Ultra",
        type: WPN_HMMR,     material: CRYS,
        score: 3000,        slots: 'SPG_5-SPG_5-SOG_5-REC-CIR|DAI',
        skill: 'AGS_SHD_3', cost: 44,
        evt: true,
    },
    {
        rcode: 1509,        name: "Indomitable Liturgical Blade",
        type: WPN_SWORD,    material: HORN,
        score: 3480,        slots: 'SPB_6-HWL_6-EFR_6-CIR-STA|TRI-CIR',
        skill: 'CSM_IMP_4', cost: 50,
        limited: true,
    },
    {
        rcode: 9038,        name: "Gold Leviathan Rod",
        type: WPN_STAFF,    material: HORN,
        score: 3120,        slots: 'ICE_10-MGR_6-HWL_5-TRI-DAI|CIR',
        skill: 'WTH_HDS_1', cost: 45,
    },
    {
        rcode: 3087,        name: "Apollon's Epic Lance",
        type: WPN_LANCE,    material: HORN,
        score: 3050,        slots: 'LHT_10-MSM_5-WLW_5-TRI-CIR',
        skill: 'JDM_RAI_3', cost: 45,
        evt: true,
    },
    {
        rcode: 3088,        name: "Hercules's Epic Hammer",
        type: WPN_HMMR,     material: HORN,
        score: 3000,        slots: 'SOG_5-QHT_5-ADH_5-TRI-TRI',
        skill: 'SPD_BMR_2', cost: 45,
        evt: true,
    },
    {
        rcode: 9035,        name: "Smashin' Bashin' Tomatoes",
        type: WPN_HMMR,     material: FRAG,
        score: 2800,        slots: 'STA-REC-TRI-CIR-TRI|CIR',
        skill: 'AGS_SHD_2', cost: 30,
        evt: true,
    },
    {
        rcode: 3155,        name: "Malefic Mephisto Blade",
        type: WPN_SWORD,    material: WOOD,
        score: 3500,        slots: 'MGR_6-HWL_6-TMV_6-TRI-STA|CIR-KIT',
        skill: 'MJR_RAG_3', cost: 50,
        limited: true,
    },
    {
        code: 'PRD_RDJ',    name: "Paradise's Radiant Jewel",
        type: WPN_FIST,     material: CRYS,
        score: 1800,        slots: 'HAS_10-QUI_10-CMB_10-ATK_10-ELF_5|STA',
        skill: 'ETR_WAV_3', cost: 45,
        evt: true,
    },
    {
        rcode: 1506,        name: "Nova Stella Rod",
        type: WPN_STAFF,    material: WOOD,
        score: 3280,        slots: 'KOH_6-MGR_6-MGR_5-TRI-KIT|TRI-STA',
        skill: 'ETR_WAV_3', cost: 45,
        limited: true,
    },
    {
        rcode: 3140,        name: "Nova Stella Lance",
        type: WPN_LANCE,    material: WOOD,
        score: 3300,        slots: 'TMV_6-HWL_6-SOG_5-DAI-KIT',
        skill: 'SAB_WTH_3', cost: 45,
        limited: true,
    },
    {
        rcode: 9039,        name: "Hard Working Brave's Honor",
        type: WPN_SWORD,    material: FRAG,
        score: 3000,        slots: 'CIR-TRI-DAI-REC-KIT',
        skill: 'AGS_SHD_2', cost: 30,
        evt: true,
    },
    {
        rcode: 3114,        name: "Big Bad Wolven Claw",
        type: WPN_FIST,     material: WOOD,
        score: 1750,        slots: 'SPB_5-BAR_5-BAR_5-BAR_5-KIT',
        skill: 'ETR_WAV_3', cost: 44,
        evt: true,
    },
    {
        rcode: 9037,        name: "Emerald Forest",
        type: WPN_HMMR,     material: WOOD,
        score: 3000,        slots: 'VSP_5-KOH_5-HEA_10-STA-TRI',
        skill: 'AIR_BST_2', cost: 0,
        evt: true,
    },
    {
        rcode: 3162,        name: "Dantalion's Despair",
        type: WPN_LANCE,    material: CRYS,
        score: 3300,        slots: 'SPB_6-HRF_6-WLW_6-TRI-CIR|KIT',
        skill: 'CSM_DNT_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3167,        name: "Jyr Yong Blade",
        type: WPN_SWORD,    material: CRYS,
        score: 3240,        slots: 'ICE_10-SPB_6-HWL_5-DAI-TRI|CIR-TRI',
        skill: 'ICB_EDG_4', cost: 45,
    },
    {
        rcode: 3152,        name: "Yong Shyr Mace",
        type: WPN_HMMR,     material: CRYS,
        score: 3170,        slots: 'DRK_10-MGR_6-SOG_5-DAI-CIR|TRI',
        skill: 'NCL_BMR_4', cost: 45,
    },
    {
        rcode: 3113,        name: "Fruit of Mountain Peaks",
        type: WPN_STAFF,    material: WOOD,
        score: 2850,        slots: 'LHT_10-SRS_5-VSP_5-CIR-TRI|TRI-CIR',
        skill: 'DEF_DES_3', cost: 50,
        evt: true,
    },
    {
        rcode: 3160,        name: "Cloven Hoof of Sleipnir",
        type: WPN_HMMR,     material: IRON,
        score: 3370,        slots: 'MGR_6-HWL_6-SOG_6-TRI-STA|CIR-TRI',
        skill: 'CSM_IMP_4', cost: 50,
        limited: true,
    },
    {
        rcode: 3128,        name: "Lethal Artillery Lance",
        type: WPN_LANCE,    material: IRON,
        score: 3180,        slots: 'WND_10-DRK_9-TMV_6-WLW_5-TRI|TRI-CIR',
        skill: 'WTH_ZPR_1', cost: 45,
    },
    {
        rcode: 3127,        name: "Lethal Rod of Ordnance",
        type: WPN_STAFF,    material: IRON,
        score: 3170,        slots: 'DRK_10-WND_9-MGR_6-EFR_5-TRI|CIR',
        skill: 'WTH_ZPR_1', cost: 45,
    },
    {
        rcode: 3139,        name: "Hollow Ark Albion X",
        type: WPN_FIST,     material: IRON,
        score: 1805,        slots: 'DRK_10-WND_10-MGR_5-DAI-CIR',
        skill: 'RIS_DRK_3', cost: 44,
        evt: true,
    },
    {
        rcode: 3161,        name: "Azazel's Thirst",
        type: WPN_STAFF,    material: FRAG,
        score: 3350,        slots: 'GTT_6-EFR_6-HWL_6-TRI-STA|CIR-CIR',
        skill: 'MJR_RAG_3', cost: 50,
        limited: true,
    },
    {
        rcode: 3168,        name: "Lamia's Vengeance",
        type: WPN_HMMR,     material: FRAG,
        score: 3400,        slots: 'SPB_6-SOG_5-EFR_6-STA-CIR|TRI',
        skill: 'CSM_DNT_3', cost: 42,
        limited: true,      publish: new Date('2015-09-25'),
    },
    {
        rcode: 3169,        name: "Lamia's Agony",
        type: WPN_STAFF,    material: FRAG,
        score: 3380,        slots: 'ELE_10-MGR_6-HWL_6-CIR-DAI|TRI-REC',
        skill: 'LHT_BMR_4', cost: 45,
        limited: true,      publish: new Date('2015-09-25'),
    },
    {
        rcode: 1505,        name: "Hollow Edge Albion X",
        type: WPN_SWORD,    material: HORN,
        score: 3090,        slots: 'SPB_5-HWL_5-MSM_5-CIR-KIT|TRI',
        skill: 'RIS_DRK_3', cost: 44,
        evt: true,          publish: new Date('2015-09-25'),
    },
    // 2015-10-02
    {
        rcode: 3150,        name: "Epoch Chronos Lance",
        type: WPN_LANCE,    material: WOOD,
        score: 3221,        slots: 'SPB_6-WLW_5-HWL_5-KIT-CIR|DAI-TRI',
        skill: 'TMP_BMR_4', cost: 45,
        publish: new Date('2015-10-02'),
    },
    {
        rcode: 3151,        name: "Epoch Chronos Rod",
        type: WPN_STAFF,     material: WOOD,
        score: 3203,        slots: 'MGR_6-HWL_5-EFR_5-TRI-TRI|TRI-DAI',
        skill: 'ETR_WAV_3', cost: 45,
        publish: new Date('2015-10-02'),
    },
    // 2015-10-05
    {
        rcode: 9041,        name: "The Hornet Queen",
        type: WPN_SWORD,    material: FRAG,
        score: 3500,        slots: 'SOG_5-SSL_5-TMV_5-CIR-STA|DAI-KIT',
        skill: 'DRN_BST_3', cost: 55,
        evt: true,          publish: new Date('2015-10-05'),
    },
    // 2015-10-06
    {
        rcode: 1517,        name: "Oriax Star",
        type: WPN_FIST,     material: IRON,
        score: 2200,       slots: 'SPB_6-EFR_6-HWL_6-REC-STA|TRI-TRI',
        skill: 'MJR_RAG_3', cost: 50,
        limited: true,      publish: new Date('2015-10-06'),
    },
    {
        rcode: 3103,        name: "Lost Key to Atlantica",
        type: WPN_FIST,     material: CRYS,
        score: 1850,        slots: 'KOH_5-SOG_5-BAR_5-REC-REC|REC-TRI',
        skill: 'DEF_DES_2', cost: 34,
        evt: true,      publish: new Date('2015-10-06'),
    },
    // 2015-10-09
    {
        rcode: 3165,        name: "Shadow's Wrath",
        type: WPN_SWORD,     material: IRON,
        score: 3280,       slots: 'DRK_10-MGR_5-HWL_5-CIR-KIT|DAI-TRI',
        skill: 'WTH_ZPR_2', cost: 45,
        publish: new Date('2015-10-09'),
    },
    {
        rcode: 3166,        name: "Shadow Piercer",
        type: WPN_LANCE,     material: IRON,
        score: 3230,        slots: 'DRK_10-HWL_5-HWL_5-REC-REC',
        skill: 'WTH_ZPR_2', cost: 45,
        publish: new Date('2015-10-09'),
    },
    // 2015-10-30
    {
        rcode: 3170,        name: "Halloween Trickster",
        type: WPN_STAFF,    material: HORN,
        score: 3660,        slots: 'EFR_5-MGR_6-EFR_6-TRI-TRI|TRI-REC',
        skill: 'SRK_BMR_4', cost: 50,
        publish: new Date('2015-10-30'),
        limited: true,
    },
    {
        rcode: 3171,        name: "Halloween Night-Reaper",
        type: WPN_SWORD,    material: HORN,
        score: 3700,        slots: 'HWL_5-MGR_6-HWL_6-CIR-TRI|CIR-KIT',
        skill: 'SRK_BMR_4', cost: 50,
        publish: new Date('2015-10-30'),
        limited: true,
    },
];
