var WOODS = [
    {
        code: 'AIN_CHA',    name: "Ainsel Chapeau",
        type: HEAD,         material: WOOD,
        score: 4171,        slots: 'BAT_5-SKL_5-ATK_5-KIT-CIR|DAI',
        cost: 35,
    },
    {
        code: 'AIN_COA',    name: "Ainsel Coat",
        type: ARMOR,        material: WOOD,
        score: 2350,        slots: 'BAT_5-HEA_5-HP_5-REC-KIT',
        cost: 35,
    },
    {
        code: 'HCR_HLM',    name: "Hachiryu's Helmet",
        type: HEAD,         material: WOOD,
        score: 4201,        slots: 'KTS_4-HEA_5-TRI-CIR-TRI|CIR',
        cost: 35,
    },
    {
        code: 'HCR_AMR',    name: "Hachiryu's Armor",
        type: ARMOR,        material: WOOD,
        score: 2288,        slots: 'KTS_4-HAS_5-QUI_5-KIT-CIR|TRI',
        cost: 35,
    },
    {
        code: 'SSN_AMR',    name: "Armor of Susano-o",
        type: ARMOR,        material: WOOD,
        score: 2563,        slots: 'LSG_5-HAS_9-SKL_10-TRI-CIR|CIR',
        limited: true,      cost: 40,
    },
    {
        code: 'YTK_HLM',    name: "Helmet of Yata no Kagami",
        type: HEAD,         material: WOOD,
        score: 4614,        slots: 'LSG_5-HEA_9-HP_10-TRI-TRI|TRI',
        limited: true,      cost: 40,
    },
    {
        code: 'BSM_STT',    name: "Balsamina Striata",
        type: HEAD,         material: WOOD,
        score: 4239,        slots: 'DVR_5-QUI_9-HEA_9-CIR-TRI|CIR',
        cost: 37,
    },
    {
        code: 'BSM_EPB',    name: "Balsamina Euphorbia",
        type: ARMOR,        material: WOOD,
        score: 2360,        slots: 'DVR_5-CMB_9-SKL_9-DAI-CIR|CIR',
        cost: 37,
    },
    {
        code: 'CLT_HLM',    name: "Celestial Helm",
        type: HEAD,         material: WOOD,
        score: 4305,        slots: 'LSG_5-HAS_9-KOH_5-TRI-KIT|TRI',
        cost: 50,
    },
    {
        code: 'CLT_MAI',    name: "Celestial Mail",
        type: ARMOR,        material: WOOD,
        score: 2432,        slots: 'LSG_5-QUI_9-HEA_10-REC-CIR|TRI',
        cost: 50,           skill: 'CHO_MTO_1',
    },
    {
        code: 'DVN_EFS',    name: "Divine Efflorescence",
        type: HEAD,         material: WOOD,
        score: 4350,        slots: 'HDB_5-QUI_10-SRS_4-TRI-KIT|CIR',
        cost: 37,
    },
    {
        code: 'PSP_BLS',    name: "Persephone's Blessing",
        type: ARMOR,        material: WOOD,
        score: 2480,        slots: 'DVR_5-HEA_10-SRS_4-TRI-DAI|TRI',
        cost: 37,
    },
    {
        rcode: 3026,        name: "Holy Blue Dragon Helmet",
        type: HEAD,         material: WOOD,
        score: 3864,        slots: 'BAT_4-SKL_5-SKA_3-KIT-REC|CIR',
        cost: 34,
    },
    {
        rcode: 3026,        name: "Holy Blue Dragon Plate",
        type: ARMOR,        material: WOOD,
        score: 2139,        slots: 'BAT_4-HAS_5-KIT-KIT-CIR|DAI',
        cost: 34,
    },
    {
        rcode: 3048,        name: "Divine Helm of Renatus+",
        type: HEAD,         material: WOOD,
        score: 4019,        slots: 'BAT_4-WNDD_5-HEA_10-CIR-TRI',
        cost: 37,           evt: true,
    },
    {
        rcode: 3048,        name: "Divine Armor of Renatus+",
        type: ARMOR,        material: WOOD,
        score: 2357,        slots: 'BAT_4-WNDD_5-SKL_10-CIR-DAI',
        cost: 37,           evt: true,
    },
    {
        rcode: 3048,        name: "Divine Helm of Renatus",
        type: HEAD,         material: WOOD,
        score: 3140,        slots: 'BAT_3-WNDD_3-HEA_3-CIR-TRI',
        cost: 31,           evt: true,
    },
    {
        rcode: 3048,        name: "Divine Armor of Renatus",
        type: ARMOR,        material: WOOD,
        score: 1753,        slots: 'BAT_3-WNDD_3-SKL_4-CIR-DAI',
        cost: 31,           evt: true,
    },
    {
        rcode: 9999,        name: "Dendron Hat",
        type: HEAD,         material: WOOD,
        score: 3140,        slots: 'KTS_3-SKA_3-SKL_3-CIR-TRI',
        cost: 0,           evt: true,
    },
    {
        rcode: 9999,        name: "Dendron Garb",
        type: ARMOR,        material: WOOD,
        score: 2003,        slots: 'KTS_3-HP_5-HEA_3-CIR-DAI',
        cost: 0,           evt: true,
    },
    {
        rcode: 3083,        name: "Quick Helm of Idaten",
        type: HEAD,         material: WOOD,
        score: 4830,        slots: 'AVG_6-HEA_10-KOH_5-TRI-REC|DAI-CIR',
        cost: 50,           limited: true,
    },
    {
        rcode: 3083,        name: "Gallant Mail of Idaten",
        type: ARMOR,        material: WOOD,
        score: 2780,        slots: 'AVG_6-SPB_5-KOH_5-DAI-TRI|CIR-REC',
        cost: 50,           limited: true,
    },
    {
        rcode: 3002,        name: "Headband of Pure Chastity",
        type: HEAD,         material: WOOD,
        score: 4570,        slots: 'HDB_5-SUR_5-SKA_10-EFR_4-TRI|REC-REC',
        cost: 42,
    },
    {
        rcode: 3002,        name: "Dress of Pure Chastity",
        type: ARMOR,        material: WOOD,
        score: 2570,        slots: 'HDB_5-FUR_5-HAS_10-DMH_4-CIR|TRI',
        cost: 42,
    },
    {
        rcode: 3085,        name: "Pop Star's Headress",
        type: HEAD,         material: WOOD,
        score: 4450,        slots: 'TOP_4-ELF_5-HEA_10-CIR-CIR|TRI',
        cost: 42,           evt: true,
    },
    {
        rcode: 3085,        name: "Pop Star's Costume",
        type: ARMOR,        material: WOOD,
        score: 2430,        slots: 'TOP_4-DSM_5-HEA_10-CIR-TRI|CIR',
        cost: 42,           evt: true,
    },
    {
        rcode: 3096,        name: "Elven Eithel Chapeau",
        type: HEAD,         material: WOOD,
        score: 4870,        slots: 'AVG_5-TMV_6-HEA_10-CIR-TRI|DAI-TRI',
        cost: 42,
    },
    {
        rcode: 3096,        name: "Elven Eithel Cuirass",
        type: ARMOR,        material: WOOD,
        score: 2770,        slots: 'AVG_5-VSP_6-SOG_5-CIR-TRI|REC-REC',
        cost: 42,
    },
    {
        rcode: 3094,        name: "Galactical Cosmos Cap",
        type: HEAD,         material: WOOD,
        score: 4380,        slots: 'KTS_5-HVH_5-WLW_4-DAI-CIR|CIR',
        cost: 42,           evt: true,
    },
    {
        rcode: 3094,        name: "Galactical Cosmos Robe",
        type: ARMOR,        material: WOOD,
        score: 2480,        slots: 'KTS_5-MGR_4-ELF_5-CIR-DAI|TRI',
        cost: 42,           evt: true,
    },
    {
        rcode: 3032,        name: "Hat in Full Bloom",
        type: HEAD,         material: WOOD,
        score: 4570,        slots: 'HDB_5-SPB_5-SCT_3-CIR-CIR|TRI',
        cost: 42,           evt: true,
    },
    {
        rcode: 3032,        name: "Summer in Full Bloom",
        type: ARMOR,        material: WOOD,
        score: 2570,        slots: 'HDB_5-NBR_5-KOH_4-TRI-KIT',
        cost: 42,            evt: true,
    },
    {
        rcode: 3093,        name: "Gallivant Viage Hat",
        type: HEAD,         material: WOOD,
        score: 4950,        slots: 'IVT_5-HEA_10-MGR_6-CIR-TRI|TRI-DAI',
        cost: 45,
    },
    {
        rcode: 3093,        name: "Gallivant Viage Coat",
        type: ARMOR,        material: WOOD,
        score: 2860,        slots: 'IVT_5-SPB_6-TMV_5-CIR-TRI|TRI-CIR',
        cost: 45,           skill: 'FRZ_OBT_3',
    },
    {
        rcode: 3103,        name: "Hat of the Stargazer",
        type: HEAD,         material: WOOD,
        score: 5120,        slots: 'LSG_6-WLW_6-HWL_5-CIR-TRI|REC-TRI',
        cost: 45,           limited: true,
    },
    {
        rcode: 3103,        name: "Robe of the Stargazer",
        type: ARMOR,        material: WOOD,
        score: 3150,        slots: 'LSG_6-SPB_6-HWL_5-TRI-TRI|CIR-DAI',
        cost: 45,           limited: true,
        skill: 'PTN_MTO_3',
    },
    {
        rcode: 9027,        name: "Highland Festive Cap",
        type: HEAD,         material: WOOD,
        score: 4800,        slots: 'HDB_5-SPB_5-VSP_5-TRI-CIR|DAI-DAI',
        cost: 45,            evt: true,
    },
    {
        rcode: 9027,        name: "Highland Festive Dress",
        type: ARMOR,        material: WOOD,
        score: 2800,        slots: 'HDB_5-SPB_5-KOH_5-TRI-KIT|TRI',
        cost: 45,            evt: true,
        skill: 'WND_SHF_3',
    },
    {
        rcode: 9999,        name: "All Hallows' Headband",
        type: HEAD,         material: WOOD,
        score: 2814,        slots: 'BAT_3-SKL_3-SKA_3-KIT-REC',
        cost: 28,            evt: true,
        name2: "All Hallows' Hat",
    },
    {
        rcode: 9999,        name: "All Hallows' Garb",
        type: ARMOR,        material: WOOD,
        score: 1323,        slots: 'BAT_3-HAS_3-KIT-KIT-REC',
        cost: 28,            evt: true,
    },
// 2015/10/02
    {
        rcode: 3110,        name: "Epoch Chrono Helm",
        type: HEAD,         material: WOOD,
        score: 5100,        slots: 'DVS_5-EFR_6-HWL_5-HEA_10-DAI|REC-TRI',
        cost: 45,
    },
    {
        rcode: 3110,        name: "Epoch Chrono Mail",
        type: ARMOR,        material: WOOD,
        score: 3120,        slots: 'DVS_5-HWL_6-HWL_5-QUI_10-KIT|CIR-REC',
        cost: 45,           skill: 'RZR_WHW_3',
    },
];
